### ISSUE TITLE
Difficulty with install on local server

### ISSUE THREAD

**Issue by biojerm** [jupyterhub/the-littlest-jupyterhub#141]
I am having difficulty installing TLJH, when I run:
```
$ curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo python3 - --admin testadmin
```

I get this output:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2682  100  2682    0     0  11510      0 --:--:-- --:--:-- --:--:-- 11510 
Checking if TLJH is already installed...
TLJH already installed, upgrading...
Upgrading TLJH installer...
Traceback (most recent call last):
  File "<stdin>", line 83, in <module>
  File "<stdin>", line 68, in main
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/tljh/hub/bin/pip', 'install', '--upgrade', 'git+https://github.com/jupyterhub/the-littlest-jupyterhub.git']' returned non-zero exit status 1.
```

checked and I have git installed:
```
$ git --version
git version 2.17.1
```

I am running the code on an onsite VM of Ubuntu.
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
antheia@antheia-VirtualBox:~$ 
```
I put some more info below in case it might be useful.  Any suggestions on next steps or debug ideas?  I have been working on in for a bit and I am stumped.  I tried looking at the suggestions in  #108, but I did not find anything to fix my problem.  Thanks in advanced for any suggestions.
 
```
$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
```

```
$ pip list
Package      Version  
------------ ---------
asn1crypto   0.24.0   
certifi      2018.4.16
cffi         1.11.5   
chardet      3.0.4    
conda        4.5.4    
cryptography 2.2.2    
idna         2.6      
pip          10.0.1   
pycosat      0.6.3    
pycparser    2.18     
pyOpenSSL    18.0.0   
PySocks      1.6.8    
requests     2.18.4   
ruamel-yaml  0.15.37  
setuptools   39.2.0   
six          1.11.0   
urllib3      1.22     
wheel        0.31.1  
```

**Comment by biojerm** [comment]
just kidding...I was able to get it to work by doing the two following commands then installing:

```
$ pip install npm
$ sudo rm -rf /opt/tljh
$ curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo python3 - --admin testadmin

```
 After re-reading #108 I saw that deleting the old install helped.  I am not sure if having npm helped (I doubt it), but i wanted to add it for completeness.

From the original error output: 
```
...
Checking if TLJH is already installed...
TLJH already installed, upgrading...  <== clue I missed
...
```

Please mark as closed.
