### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by dzarlax** [jupyterhub/the-littlest-jupyterhub#148]
Hi!
Trying to install, but get an error:
```
dzarlax@Jupiter:~$ curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo python3 - --admin dzarlax
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2682  100  2682    0     0  13211      0 --:--:-- --:--:-- --:--:-- 13211
Checking if TLJH is already installed...
TLJH already installed, upgrading...
Upgrading TLJH installer...
Setup tljh package
Starting TLJH installer...
Setting up admin users
Granting passwordless sudo to JupyterHub admins...
Setting up user environment...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 432, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 413, in main
    ensure_user_environment(args.user_requirements_txt_url)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 229, in ensure_user_environment
    'conda==4.5.8'
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/conda.py", line 103, in ensure_conda_packages
    output = json.loads(filtered_output.lstrip('\x00'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 7 column 1 (char 82)

```

**Comment by yuvipanda** [comment]
Thanks for opening the issue, @dzarlax! Can you tell me what base operating system this is using? Did you follow one of our cloud provider guides or is this on a system by itself?

**Comment by wrightaprilm** [comment]
I have the same issue on Ubuntu 18.04, working from [this](https://the-littlest-jupyterhub.readthedocs.io/en/latest/install/custom-server.html) tutorial on my own server.

**Comment by dzarlax** [comment]
Hi @yuvipanda. I have latest Ubuntu 18.4/18.5, I don’t remember correctly on Hetzner VPS. I used tutorial for own server, the same as @wrightaprilm mentioned.

**Comment by wrightaprilm** [comment]
Works for me! Will be testing it in class today.

Thanks so much for your help, @yuvipanda!

**Comment by scottkleinman** [comment]
I'm encountering a problem on a Google Cloud install at a similar (slightly earlier?) location in the pipeline. Running the startup script from the command line gets me the following error:

```
Checking if TLJH is already installed...
Setting up hub environment
Installed python & virtual environment
Set up hub virtual environment
Setting up TLJH installer...
Setup tljh package
Starting TLJH installer...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/tljh/hub/lib/python3.5/site-packages/tljh/installer.py", line 95
    apt.add_source('nodesource', f'https://deb.nodesource.com/node_8.x', 'main')
                                                                      ^
SyntaxError: invalid syntax
```
It looks like the `npm` resources are failing to install. Any advice?

**Comment by scottkleinman** [comment]
Thanks, @yuvipanda. I thought I might have clicked the wrong option, but the boot disk source image reads `ubuntu-minimal-1804-bionic-v20180814`.

**Comment by yuvipanda** [comment]
@scottkleinman ah, there's an entry for Ubuntu 18.04 minimal, but also one for Ubuntu 18.04. The minimal won't work, you need the 'regular' one

**Comment by dzarlax** [comment]
@yuvipanda  Can you please help me?

**Comment by pintman** [comment]
I get similar problems on a Ubuntu 18.04 server on a hetzner cloud instance.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 447, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 429, in main
    ensure_user_environment(args.user_requirements_txt_url)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 248, in ensure_user_environment
    'nbresuse==0.3.0'
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/conda.py", line 120, in ensure_pip_packages
    ] + packages, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/tljh/user/bin/python', '-m', 'pip', 'install', '--no-cache-dir', 'jupyterhub==0.9.2', 'notebook==5.6.0', 'jupyterlab==0.34.1', 'nteract-on-jupyter==1.8.1', 'nbgitpuller==0.6.1', 'nbresuse==0.3.0']' returned non-zero exit status 1.

root@jupyterhub ~ # uname -a
Linux jupyterhub 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

root@jupyterhub ~ # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

```

**Comment by janbucher** [comment]
The problem persists for Hetzner Cloud Servers. I manually installed Anaconda and got rid of that "error", but it will still end in above described failure..
