### ISSUE TITLE
Timeout starting User's Jupyter Service

### ISSUE THREAD

**Issue by suhailrehman** [jupyterhub/the-littlest-jupyterhub#180]
Have been trying to get this to work, but always get a spawning timeout when starting the individual jupyterhub server for a user, logs indicate an import issue. Have followed all instructions as noted in the main page.

```
Sep 14 13:12:49 suhail-lab systemd[1]: Started /bin/bash -c cd /home/jupyter-suhail && exec jupyterhub-singleuser --port=55541.
Sep 14 13:12:50 suhail-lab bash[2722]: Traceback (most recent call last):
Sep 14 13:12:50 suhail-lab bash[2722]:   File "/opt/tljh/user/bin/jupyterhub-singleuser", line 3, in <module>
Sep 14 13:12:50 suhail-lab bash[2722]:     from jupyterhub.singleuser import main
Sep 14 13:12:50 suhail-lab bash[2722]:   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 34, in <module>
Sep 14 13:12:50 suhail-lab bash[2722]:     from notebook.notebookapp import (
Sep 14 13:12:50 suhail-lab bash[2722]:   File "/opt/tljh/user/lib/python3.6/site-packages/notebook/notebookapp.py", line 80, in <module>
Sep 14 13:12:50 suhail-lab bash[2722]:     from .services.kernels.kernelmanager import MappingKernelManager
Sep 14 13:12:50 suhail-lab bash[2722]:   File "/opt/tljh/user/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 19, in <module>
Sep 14 13:12:50 suhail-lab bash[2722]:     from jupyter_client.session import Session
Sep 14 13:12:50 suhail-lab bash[2722]:   File "/opt/tljh/user/lib/python3.6/site-packages/jupyter_client/session.py", line 61, in <module>
Sep 14 13:12:50 suhail-lab bash[2722]:     from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
Sep 14 13:12:50 suhail-lab bash[2722]:   File "/opt/tljh/user/lib/python3.6/site-packages/jupyter_client/jsonutil.py", line 11, in <module>
Sep 14 13:12:50 suhail-lab bash[2722]:     from dateutil.parser import parse as _dateutil_parse
Sep 14 13:12:50 suhail-lab bash[2722]: ModuleNotFoundError: No module named 'dateutil'
Sep 14 13:12:50 suhail-lab systemd[1]: jupyter-suhail.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 13:12:50 suhail-lab systemd[1]: jupyter-suhail.service: Failed with result 'exit-code'.
Sep 14 13:15:13 suhail-lab systemd[1]: Started /bin/bash -c cd /home/jupyter-suhail && exec jupyterhub-singleuser --port=55541.
Sep 14 13:15:13 suhail-lab bash[3029]: Traceback (most recent call last):
Sep 14 13:15:13 suhail-lab bash[3029]:   File "/opt/tljh/user/bin/jupyterhub-singleuser", line 3, in <module>
Sep 14 13:15:13 suhail-lab bash[3029]:     from jupyterhub.singleuser import main
Sep 14 13:15:13 suhail-lab bash[3029]:   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 34, in <module>
Sep 14 13:15:13 suhail-lab bash[3029]:     from notebook.notebookapp import (
Sep 14 13:15:13 suhail-lab bash[3029]:   File "/opt/tljh/user/lib/python3.6/site-packages/notebook/notebookapp.py", line 80, in <module>
Sep 14 13:15:13 suhail-lab bash[3029]:     from .services.kernels.kernelmanager import MappingKernelManager
Sep 14 13:15:13 suhail-lab bash[3029]:   File "/opt/tljh/user/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 19, in <module>
Sep 14 13:15:13 suhail-lab bash[3029]:     from jupyter_client.session import Session
Sep 14 13:15:13 suhail-lab bash[3029]:   File "/opt/tljh/user/lib/python3.6/site-packages/jupyter_client/session.py", line 61, in <module>
Sep 14 13:15:13 suhail-lab bash[3029]:     from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
Sep 14 13:15:13 suhail-lab bash[3029]:   File "/opt/tljh/user/lib/python3.6/site-packages/jupyter_client/jsonutil.py", line 11, in <module>
Sep 14 13:15:13 suhail-lab bash[3029]:     from dateutil.parser import parse as _dateutil_parse
Sep 14 13:15:13 suhail-lab bash[3029]: ModuleNotFoundError: No module named 'dateutil'
Sep 14 13:15:13 suhail-lab systemd[1]: jupyter-suhail.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 13:15:13 suhail-lab systemd[1]: jupyter-suhail.service: Failed with result 'exit-code'.
```

**Comment by JulianKling** [comment]
Same problem for me ATM

**Comment by EdenTDatalytyx** [comment]
Solved this by doing the following: 
`
sudo su -
source /opt/tljh/user/bin/activate
pip install python-dateutil
source /opt/tljh/user/bin/deactivate
exit
`

This should get you into the virtual environment that was created by root to run the server in, then install the right module, then exit you out again.

**Comment by Funatiq** [comment]
Thank you for the solution. Why is this still not fixed?
