### ISSUE TITLE
Exception: Installation failed: JupyterHub did not start in 4s

### ISSUE THREAD

**Issue by vnijs** [jupyterhub/the-littlest-jupyterhub#183]
Just tried out `the-littlest-jupyterhub` but ran into an issue. See output below. 

```
curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo python3 - --admin vnijs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2682  100  2682    0     0  11560      0 --:--:-- --:--:-- --:--:-- 11510
Checking if TLJH is already installed...
Setting up hub environment
Installed python & virtual environment
Set up hub virtual environment
Setting up TLJH installer...
Setup tljh package
Starting TLJH installer...
Downloading traefik 1.6.5...
> /usr/bin/npm pack @jupyterlab/hub-extension
> node /opt/tljh/user/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
> node /opt/tljh/user/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build
Created symlink /etc/systemd/system/multi-user.target.wants/jupyterhub.service → /etc/systemd/system/jupyterhub.service.
Created symlink /etc/systemd/system/multi-user.target.wants/configurable-http-proxy.service → /etc/systemd/system/configurable-http-proxy.service.
Created symlink /etc/systemd/system/multi-user.target.wants/traefik.service → /etc/systemd/system/traefik.service.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 447, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 437, in main
    ensure_jupyterhub_running()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 304, in ensure_jupyterhub_running
    raise Exception("Installation failed: JupyterHub did not start in {}s".format(times))
Exception: Installation failed: JupyterHub did not start in 4s
```

**Comment by vnijs** [comment]
Tried the same install process and it worked the 2nd time!

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/tljh-fails-to-install/5463/1
