### ISSUE TITLE
Spawner errors after restarting hub

### ISSUE THREAD

**Issue by jhamman** [jupyterhub/the-littlest-jupyterhub#191]
I have a Littlest JupyterHub running on GCP. After shutting the hub down and restarting it I am no longer able to spawn notebook servers:

![image](https://user-images.githubusercontent.com/2443309/46302047-f43b7300-c55c-11e8-81c5-2adf1b34e5b6.png)

Looking at the logs:

```
$ sudo journalctl -u jupyterhub
Oct 01 16:30:35 acf-jhub python3[1142]: [I 2018-10-01 16:30:35.199 JupyterHub base:499] User logged in: jhamman
Oct 01 16:30:35 acf-jhub python3[1142]: [I 2018-10-01 16:30:35.201 JupyterHub log:158] 302 POST /hub/login?next= -> /user/jhamman/ (jhamman@128.117.65.36) 313.42ms
Oct 01 16:30:35 acf-jhub python3[1142]: [I 2018-10-01 16:30:35.300 JupyterHub log:158] 302 GET /user/jhamman/ -> /hub/user/jhamman/ (@128.117.65.36) 0.76ms
Oct 01 16:30:35 acf-jhub python3[1142]: [E 2018-10-01 16:30:35.409 JupyterHub base:1001] Preventing implicit spawn for jhamman because last spawn failed: Timeout
Oct 01 16:30:35 acf-jhub python3[1142]: [E 2018-10-01 16:30:35.409 JupyterHub web:1670] Uncaught exception GET /hub/user/jhamman/ (128.117.65.36)
Oct 01 16:30:35 acf-jhub python3[1142]:     HTTPServerRequest(protocol='http', host='acf-hub.joehamman.com', method='GET', uri='/hub/user/jhamman/', version='HTTP/1.1', remote_ip='1
Oct 01 16:30:35 acf-jhub python3[1142]:     Traceback (most recent call last):
Oct 01 16:30:35 acf-jhub python3[1142]:       File "/opt/tljh/hub/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
Oct 01 16:30:35 acf-jhub python3[1142]:         result = yield result
Oct 01 16:30:35 acf-jhub python3[1142]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 1003, in get
Oct 01 16:30:35 acf-jhub python3[1142]:         raise copy.copy(exc).with_traceback(exc.__traceback__)
Oct 01 16:30:35 acf-jhub python3[1142]:       File "/opt/tljh/hub/lib/python3.6/site-packages/tornado/gen.py", line 970, in error_callback
Oct 01 16:30:35 acf-jhub python3[1142]:         future.result()
Oct 01 16:30:35 acf-jhub python3[1142]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
Oct 01 16:30:35 acf-jhub python3[1142]:         await spawn_future
Oct 01 16:30:35 acf-jhub python3[1142]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/user.py", line 486, in spawn
Oct 01 16:30:35 acf-jhub python3[1142]:         raise e
Oct 01 16:30:35 acf-jhub python3[1142]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/user.py", line 406, in spawn
Oct 01 16:30:35 acf-jhub python3[1142]:         url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
Oct 01 16:30:35 acf-jhub python3[1142]:     tornado.util.TimeoutError: Timeout
Oct 01 16:30:35 acf-jhub python3[1142]:     
Oct 01 16:30:35 acf-jhub python3[1142]: [E 2018-10-01 16:30:35.412 JupyterHub log:150] {
Oct 01 16:30:35 acf-jhub python3[1142]:       "X-Real-Ip": "128.117.65.36",
Oct 01 16:30:35 acf-jhub python3[1142]:       "X-Forwarded-Server": "acf-jhub",
Oct 01 16:30:35 acf-jhub python3[1142]:       "X-Forwarded-Proto": "https,http",
Oct 01 16:30:35 acf-jhub python3[1142]:       "X-Forwarded-Port": "443,80",
Oct 01 16:30:35 acf-jhub python3[1142]:       "X-Forwarded-Host": "acf-hub.joehamman.com",
Oct 01 16:30:35 acf-jhub python3[1142]:       "X-Forwarded-For": "128.117.65.36,127.0.0.1",
Oct 01 16:30:35 acf-jhub python3[1142]:       "Referer": "https://acf-hub.joehamman.com/hub/login",
Oct 01 16:30:35 acf-jhub python3[1142]:       "Origin": "https://acf-hub.joehamman.com",
Oct 01 16:30:35 acf-jhub python3[1142]:       "Cookie": "jupyterhub-hub-login=\"2|1:0|10:1538411435|20:jupyterhub-hub-login|44:HASH=|77d6e0ca7
Oct 01 16:30:35 acf-jhub python3[1142]:       "Accept-Language": "en-us",
Oct 01 16:30:35 acf-jhub python3[1142]:       "Accept-Encoding": "br, gzip, deflate",
Oct 01 16:30:35 acf-jhub python3[1142]:       "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
Oct 01 16:30:35 acf-jhub python3[1142]:       "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15",
Oct 01 16:30:35 acf-jhub python3[1142]:       "Host": "acf-hub.joehamman.com",
Oct 01 16:30:35 acf-jhub python3[1142]:       "Connection": "close"
Oct 01 16:30:35 acf-jhub python3[1142]:     }
Oct 01 16:30:35 acf-jhub python3[1142]: [E 2018-10-01 16:30:35.412 JupyterHub log:158] 500 GET /hub/user/jhamman/ (jhamman@128.117.65.36) 11.72ms
Oct 01 16:30:43 acf-jhub python3[1142]: [I 2018-10-01 16:30:43.377 JupyterHub log:158] 200 GET /hub/home (jhamman@128.117.65.36) 10.43ms
Oct 01 16:30:45 acf-jhub python3[1142]: [I 2018-10-01 16:30:45.062 JupyterHub log:158] 302 GET /hub/spawn -> /user/jhamman/ (jhamman@128.117.65.36) 9.87ms
Oct 01 16:30:45 acf-jhub python3[1142]: [I 2018-10-01 16:30:45.162 JupyterHub log:158] 302 GET /user/jhamman/ -> /hub/user/jhamman/ (@128.117.65.36) 0.71ms
Oct 01 16:30:45 acf-jhub python3[1142]: Failed to start transient service unit: Unit jupyter-jhamman.service already exists.
Oct 01 16:30:55 acf-jhub python3[1142]: [W 2018-10-01 16:30:55.271 JupyterHub base:714] User jhamman is slow to start (timeout=10)
Oct 01 16:30:55 acf-jhub python3[1142]: [I 2018-10-01 16:30:55.271 JupyterHub base:1056] jhamman is pending spawn
Oct 01 16:30:55 acf-jhub python3[1142]: [I 2018-10-01 16:30:55.274 JupyterHub log:158] 200 GET /hub/user/jhamman/ (jhamman@128.117.65.36) 10014.98ms
Oct 01 16:31:45 acf-jhub python3[1142]: [W 2018-10-01 16:31:45.306 JupyterHub user:468] jhamman's server failed to start in 60 seconds, giving up
Oct 01 16:31:45 acf-jhub python3[1142]: [E 2018-10-01 16:31:45.336 JupyterHub gen:974] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_sp
Oct 01 16:31:45 acf-jhub python3[1142]:     Traceback (most recent call last):
Oct 01 16:31:45 acf-jhub python3[1142]:       File "/opt/tljh/hub/lib/python3.6/site-packages/tornado/gen.py", line 970, in error_callback
Oct 01 16:31:45 acf-jhub python3[1142]:         future.result()
Oct 01 16:31:45 acf-jhub python3[1142]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
Oct 01 16:31:45 acf-jhub python3[1142]:         await spawn_future
Oct 01 16:31:45 acf-jhub python3[1142]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/user.py", line 486, in spawn
Oct 01 16:31:45 acf-jhub python3[1142]:         raise e
Oct 01 16:31:45 acf-jhub python3[1142]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/user.py", line 406, in spawn
Oct 01 16:31:45 acf-jhub python3[1142]:         url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
Oct 01 16:31:45 acf-jhub python3[1142]:     tornado.util.TimeoutError: Timeout
Oct 01 16:31:45 acf-jhub python3[1142]:     
Oct 01 16:31:45 acf-jhub python3[1142]: [I 2018-10-01 16:31:45.337 JupyterHub log:158] 200 GET /hub/api/users/jhamman/server/progress (jhamman@128.117.65.36) 49927.85ms
Oct 01 16:33:48 acf-jhub python3[1142]: [I 2018-10-01 16:33:48.855 JupyterHub proxy:301] Checking routes
Oct 01 16:38:48 acf-jhub python3[1142]: [I 2018-10-01 16:38:48.855 JupyterHub proxy:301] Checking routes
```

```
$ sudo journalctl -u jupyter-jhamman
Oct 01 16:26:17 acf-jhub systemd[1]: Started /bin/bash -c cd /home/jupyter-jhamman && exec jupyterhub-singleuser --port=52547.
Oct 01 16:26:17 acf-jhub bash[2970]: Traceback (most recent call last):
Oct 01 16:26:17 acf-jhub bash[2970]:   File "/opt/tljh/user/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 10, in <module>
Oct 01 16:26:17 acf-jhub bash[2970]:     import sqlite3
Oct 01 16:26:17 acf-jhub bash[2970]:   File "/opt/tljh/user/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
Oct 01 16:26:17 acf-jhub bash[2970]:     from sqlite3.dbapi2 import *
Oct 01 16:26:17 acf-jhub bash[2970]:   File "/opt/tljh/user/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
Oct 01 16:26:17 acf-jhub bash[2970]:     from _sqlite3 import *
Oct 01 16:26:17 acf-jhub bash[2970]: ImportError: libncurses.so.6: cannot open shared object file: No such file or directory
Oct 01 16:26:17 acf-jhub bash[2970]: During handling of the above exception, another exception occurred:
Oct 01 16:26:17 acf-jhub bash[2970]: Traceback (most recent call last):
Oct 01 16:26:17 acf-jhub bash[2970]:   File "/opt/tljh/user/bin/jupyterhub-singleuser", line 3, in <module>
Oct 01 16:26:17 acf-jhub bash[2970]:     from jupyterhub.singleuser import main
Oct 01 16:26:17 acf-jhub bash[2970]:   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 34, in <module>
Oct 01 16:26:17 acf-jhub bash[2970]:     from notebook.notebookapp import (
Oct 01 16:26:17 acf-jhub bash[2970]:   File "/opt/tljh/user/lib/python3.6/site-packages/notebook/notebookapp.py", line 85, in <module>
Oct 01 16:26:17 acf-jhub bash[2970]:     from .services.sessions.sessionmanager import SessionManager
Oct 01 16:26:17 acf-jhub bash[2970]:   File "/opt/tljh/user/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 13, in <module>
Oct 01 16:26:17 acf-jhub bash[2970]:     from pysqlite2 import dbapi2 as sqlite3
Oct 01 16:26:17 acf-jhub bash[2970]: ModuleNotFoundError: No module named 'pysqlite2'
Oct 01 16:26:17 acf-jhub systemd[1]: jupyter-jhamman.service: Main process exited, code=exited, status=1/FAILURE
Oct 01 16:26:17 acf-jhub systemd[1]: jupyter-jhamman.service: Failed with result 'exit-code'.
```

The main thing I'm seeing is that jupyter is looking for `pysqlite2` and can't find it.

**Comment by jhamman** [comment]
I was able to resolve this by updating jupyterhub and SQLAlchemy:

```
sudo /opt/tljh/hub/bin/pip install jupyterhub --upgrade
```
then restarting the hub again.

**Comment by minrk** [comment]
If it's importing pysqlite2 that's already off to a bad start because the stdlib sqlite3 doesn't work. That shouldn't happen with conda packages, so something must be off, either a broken package or something wrong with dynamic library loading

**Comment by yuvipanda** [comment]
I suspect thIs might be because the minimal Ubuntu image was used rather than the full image. Since this issue is a bit old, I am gonna close this one, @jhamman. LMK if this recurs.

**Comment by jhamman** [comment]
@yuvipanda - I'm not using tljh at the moment and since I was able to fix this up using the work around shown above, I'd be fine to see this closed. Up to you.
