### ISSUE TITLE
cannot import tensorflow-gpu

### ISSUE THREAD

**Issue by mmatiaschek** [jupyterhub/the-littlest-jupyterhub#208]
i installed tensorflow-gpu and all necessary drivers, CUDA and cuDNN.
`import tensorflow` works in the terminal but not in a TLJH notebook.
I get the following error:
`ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory`

I have tried multiple ways to set `LD_LIBRARY_PATH` in the notebook and eventually that seems to have worked, but still i cannot import tensorflow.

full stacktrace for `import tensorflow as tf` in tljh:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/opt/tljh/user/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

/opt/tljh/user/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

/opt/tljh/user/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

/opt/tljh/user/lib/python3.6/imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

/opt/tljh/user/lib/python3.6/imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-2-64156d691fe5> in <module>
----> 1 import tensorflow as tf

/opt/tljh/user/lib/python3.6/site-packages/tensorflow/__init__.py in <module>
     20 
     21 # pylint: disable=g-bad-import-order
---> 22 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     23 
     24 try:

/opt/tljh/user/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

/opt/tljh/user/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/tljh/user/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/tljh/user/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/tljh/user/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/tljh/user/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
In the tljh terminal:
```
jupyter-mmatiaschek@gpu-hub:~$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
/opt/tljh/user/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/tljh/user/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
>>>
```

result of `%env`:
```
{'JUPYTERHUB_CLIENT_ID': 'jupyterhub-user-mmatiaschek',
 'LANG': 'C.UTF-8',
 'OLDPWD': '/home/jupyter-mmatiaschek',
 'INVOCATION_ID': 'f47ef28c5361449bbbff0b8c5f9c0046',
 'USER': 'jupyter-mmatiaschek',
 'JUPYTERHUB_BASE_URL': '/',
 'PWD': '/home/jupyter-mmatiaschek',
 'HOME': '/home/jupyter-mmatiaschek',
 'JOURNAL_STREAM': '9:21350',
 'JUPYTERHUB_USER': 'mmatiaschek',
 'JUPYTERHUB_SERVICE_PREFIX': '/user/mmatiaschek/',
 'SHELL': '/bin/bash',
 'JUPYTERHUB_API_URL': 'http://127.0.0.1:15001/hub/api',
 'SHLVL': '0',
 'JUPYTERHUB_HOST': '',
 'JPY_API_TOKEN': '1ae683be8ae448168b9202562d2aafb0',
 'LOGNAME': 'jupyter-mmatiaschek',
 'JUPYTERHUB_OAUTH_CALLBACK_URL': '/user/mmatiaschek/oauth_callback',
 'JUPYTERHUB_API_TOKEN': '1ae683be8ae448168b9202562d2aafb0',
 'PATH': '/opt/tljh/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
 'JPY_PARENT_PID': '1432',
 'LD_LIBRARY_PATH': '/usr/local/cuda-9.0/lib64',
 'TERM': 'xterm-color',
 'CLICOLOR': '1',
 'PAGER': 'cat',
 'GIT_PAGER': 'cat',
 'MPLBACKEND': 'module://ipykernel.pylab.backend_inline'}
```

**Comment by mmatiaschek** [comment]
My solution was to install tensorflow-gpu using conda.
`sudo -E conda install -y tensorflow-gpu keras pandas`...
Also i am now using current nvidia 410 driver and CUDA 10. Works fine with JupyterHub and keras. Might be a problem for pytorch users.

**Comment by choldgraf** [comment]
great to hear this got resolved...IME using conda is how I solve these kinds of problems even locally as opposed to on a jupyterhub haha
