### ISSUE TITLE
Install fails 403: Forbidden

### ISSUE THREAD

**Issue by yusufk** [jupyterhub/the-littlest-jupyterhub#223]
Hi,

I keep getting a failure on install at this point:
`
curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo -E python3 - --admin yusuf

Checking if TLJH is already installed...
TLJH already installed, upgrading...
Upgrading TLJH installer...
Setup tljh package
Starting TLJH installer...
Node v8.12.0

> /usr/bin/npm pack @jupyterlab/hub-extension
Node v8.12.0

> node /opt/tljh/user/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
> node /opt/tljh/user/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 447, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 437, in main
    ensure_jupyterhub_running()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 287, in ensure_jupyterhub_running
    urlopen('http://127.0.0.1')
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

I am using a proxy and have set the proxy for npm and for bash. Am I missing something?

**Comment by tkang007** [comment]
403 Forbidden might be related with proxy server authentication.   

I met a different  error, timeout on the ensure_juupyter_running(timeout=4) when set http_proxy, https_proxy and no_proxy even though no_proxy include 127.0.0.1.  Same error was happened with wget command. It was not happened when using localhost instead of the ip when set no_proxy='localhost, 127.0.0.1', It could be avoided when set no_proxy='127.0.0.1, localhost'.  
My environment is VirtutualBox, Vagrant, vagrant-proxyconf plugin at Windows 7.  

I think the default timeout=4 seconds could a little small value.

**Comment by yusufk** [comment]
I suspect proxy issued too, but I've set whatever I can, including no_proxy

**Comment by yusufk** [comment]
Ok, I was stupid. Check my no_proxy export and it had 127.0.1.1 instead of 127.0.0.1. Apologies
