### ISSUE TITLE
nbgitpuller is failing to pull from repo (GHE)

### ISSUE THREAD

**Issue by fm75** [jupyterhub/the-littlest-jupyterhub#226]
TLJH is configured for GHE OAuth.

Our GHE is not exposed to the internet. Our proxies direct the browser direct with domain being used.

I set up a link using the [`nbgitpuller` notebook](https://hub.mybinder.org/user/jupyterhub-nbgitpuller-t51jegdq/notebooks/binder/link_generator.ipynb). Regardless of whether I tried to clone the repo, or select a specific notebook, it seems to have failed to read the `Username`. I also tried the link in an incognito window. I think that the error might be due to a failure to force me through the github authorization screen.

```bash
$ git clone https://bbgithub.dev.bloomberg.com/fred/Meetup-Comdbg-Struct-Attr Meetup-Comdbg-Struct-Attr
Cloning into 'Meetup-Comdbg-Struct-Attr'...
fatal: could not read Username for 'https://bbgithub.dev.bloomberg.com': No such device or address
Traceback (most recent call last):
File "/opt/tljh/user/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
File "/opt/tljh/user/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
File "/opt/tljh/user/lib/python3.6/site-packages/nbgitpuller/handlers.py", line 73, in pull
    raise e
File "/opt/tljh/user/lib/python3.6/site-packages/nbgitpuller/handlers.py", line 67, in pull
    for line in gp.pull():
File "/opt/tljh/user/lib/python3.6/site-packages/nbgitpuller/pull.py", line 57, in pull
    yield from self.initialize_repo()
File "/opt/tljh/user/lib/python3.6/site-packages/nbgitpuller/pull.py", line 67, in initialize_repo
    yield from execute_cmd(['git', 'clone', self.git_url, self.repo_dir])
File "/opt/tljh/user/lib/python3.6/site-packages/nbgitpuller/pull.py", line 41, in execute_cmd
    raise subprocess.CalledProcessError(ret, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://bbgithub.dev.bloomberg.com/fred/Meetup-Comdbg-Struct-Attr', 'Meetup-Comdbg-Struct-Attr']' returned non-zero exit status 128.
```

**Comment by fm75** [comment]
More info. I got someone else to run the link who was completely logged off and also in incognito browser. He did go through the OAuth and after that succeeded, got the same error.

**Comment by minrk** [comment]
Maybe you need additional initialization of the home directory to setup some git config?

**Comment by minrk** [comment]
Can you run the clone in a terminal on the same machine and work out what's missing?

**Comment by fm75** [comment]
I can clone it mysefl using https with username and access token for password when prompted in terminal.

**Comment by minrk** [comment]
ah, yes. For nbgitpuller to work, it has to be able to pull without a prompt. This might mean setting access tokens in the env, for instance, or even creating some git config.

**Comment by yuvipanda** [comment]
Apologies for the very late response.

I think we can generalize this to 'private repository access', and that should work for GHE, private repos on GitHub, etc.

I'd say the way to do this is with a readonly deploy key, set up with global git config.
