### ISSUE TITLE
Fails to install, can't find `jupyter` on 18.04

### ISSUE THREAD

**Issue by cpmpercussion** [jupyterhub/the-littlest-jupyterhub#240]
Hi all, I'm having trouble installing on Ubuntu 18.04.1 LTS. The installer can't find the `jupyter` script in the install location---any thoughts?

`Checking if TLJH is already installed...
TLJH already installed, upgrading...
Upgrading TLJH installer...
Setup tljh package
Starting TLJH installer...

==> WARNING: A newer version of conda exists. <==
  current version: 4.5.8
  latest version: 4.5.11

Please update conda by running

    $ conda update -n base conda

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 445, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 433, in main
    ensure_jupyterlab_extensions()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 172, in ensure_jupyterlab_extensions
    ] + extensions)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/tljh/user/bin/jupyter': '/opt/tljh/user/bin/jupyter'
`

**Comment by yuvipanda** [comment]
@cpmpercussion thanks for reporting this! Can you:

1. Remove the current install by doing `sudo rm -rf /opt/tljh/`
2. Try running the installer again?

**Comment by cpmpercussion** [comment]
Ok, tried removing the current install and ended up with the same error (pasted below).

The python install on this system could be in some bad state, but weird that its missing jupyter in the tljh install folder. Any thoughts?

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3550  100  3550    0     0  15990      0 --:--:-- --:--:-- --:--:-- 15990
Checking if TLJH is already installed...
Setting up hub environment
Installed python & virtual environment
Set up hub virtual environment
Setting up TLJH installer...
Setup tljh package
Starting TLJH installer...
Downloading traefik 1.6.5...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 445, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 433, in main
    ensure_jupyterlab_extensions()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 172, in ensure_jupyterlab_extensions
    ] + extensions)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/tljh/user/bin/jupyter': '/opt/tljh/user/bin/jupyter'
```

**Comment by mpkirby** [comment]
def ensure_jupyterlab_extensions():
    """
    Install the JupyterLab extensions we want.
    """
    extensions = [
        '@jupyterlab/hub-extension'
    ]
    subprocess.check_output([
        os.path.join(USER_ENV_PREFIX, 'bin/jupyter'),
        'labextension',
        'install'
    ] + extensions)



These seems to be the code in question

But on the disk
mpk@ubuntu:/opt/tljh/user/bin$ ls jupyter-*
jupyter-bundlerextension  jupyter-labhub       jupyter-nteract
jupyter-lab               jupyter-nbextension  jupyter-serverextension
jupyter-labextension      jupyter-notebook

Just the scripts, no directory "jupyter"

Did this code not match the installer?  So we should see a jupyter/labextension/install?

Mike

**Comment by fm75** [comment]
I have seen this, too. I thought that removing /opt/tljh "fixed" it. Should we update the version of conda that gets installed.  In `tljh/installer.py`, `ensure_jupyterlab_extensions` is one of approximately 10 functions that do not do any logging.

I have not figured out why this fails on the reinstall and not on the initial install since it is called in either case. I suspect that the problem is in `tljh/conda.py.ensure_conda_packages`.

**Comment by gvdr** [comment]
Encountering this issue too. Is a solution known?

**Comment by fm75** [comment]
@mpkirby 
> subprocess.check_output([
> os.path.join(USER_ENV_PREFIX, 'bin/jupyter'),
> 'labextension',
> 'install'
> ] + extensions)

This should be attempting to run
```bash
/opt/tljh/user/bin/jupyter labextension install @jupyterlab/hub-extension
```
which sets up the jupyterlab hub-extension. It looks like that worked for you. I think you were looking  for something slightly different. `jupyter` was not a directory there. (Also was not jupyterhub in your later comment.)

**Comment by fm75** [comment]
@cpmpercussion 
> Ok, tried removing the current install and ended up with the same error (pasted below).
> 
> The python install on this system could be in some bad state, but weird that it's missing jupyter in the tljh install folder. Any other ideas?

If you are still seeing this, could you try yuvi's suggestion:
```bash
sudo rm -rf /opt/tljh/
```
then:
```bash
ls -l /opt/tljh
```
should show a file not found message.
Then use the bootstrap command. If that fails, please show the output from `ls` and the exact command used for bootstrapping and the output.
I think the bootstrapping part should have created `/opt/tljh/user/bin/jupyter` by the time it gets there. 

If it is still not working, the logging may supply better information this time. A recent PR should have exposed additional logging that might help track this down.

**Comment by gvdr** [comment]
The `sudo rm -rf /opt/tljh` works fine. The `ls` returns the expected error.

I used the bootstrap command given by the readme:

`curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo -E python3 - --admin MyAdminUserName`.

If you don't mind I can provide the output of my `/opt/tljh` after the attemp to install.

the /opt/tljh tree after the installation attempt:

[tree_install_tlhj.txt](https://github.com/jupyterhub/the-littlest-jupyterhub/files/2688258/tree_install_tlhj.txt)

the installation logs:
```
2018-12-17 23:35:05,200 Checking if TLJH is already installed...
2018-12-17 23:35:05,200 Setting up hub environment
2018-12-17 23:35:08,735 Installed python & virtual environment
2018-12-17 23:35:10,389 Set up hub virtual environment
2018-12-17 23:35:10,389 Setting up TLJH installer...
2018-12-17 23:35:17,315 Setup tljh package
2018-12-17 23:35:17,316 Starting TLJH installer...
2018-12-17 23:35:17,524 Setting up admin users
2018-12-17 23:35:17,530 Granting passwordless sudo to JupyterHub admins...
2018-12-17 23:35:17,530 Setting up user environment...
2018-12-17 23:35:17,531 Downloading & setting up user environment...
2018-12-17 23:36:23,504 Setting up JupyterHub...
```

Let me know if you'd need any specific logging information

**Comment by fm75** [comment]
@gvdr @cpmpercussion 
I don't see how this is happening. From my read of `bootstrap.py` and `installer.py`, the removal of `/opt/tljh` should make it behave like a first install. From the log, it appears that is has behaved as expected up to the point of the exception.  I will try to add more logging. 

That message is emitted while executing `ensure_jupyterlab_extensions()`. By the time it gets there, it has already installed jupyterhub by `ensure_jupyterhub_package(HUB_ENV_PREFIX)`. I don't see an explicit install of jupyter via pip or conda,, but surely jupyterhub depends on jupyter, so jupyter should have been installed in `/opt/tljh/user/bin` by pip install of jupyterhub.

@yuvipanda 
Do you see what might be causing this? Is my analysis wrong?

**Comment by gvdr** [comment]
:open_mouth: 

Ok, I did the exact procedure one more time. The *exact* same procedure one more time, just because why not.

And... `Done!`.

Me happy and confused :laughing: 

Is there any logging information you'd like to read?

**Comment by gvdr** [comment]
not yet up and running, but closer a step ;-)

**Comment by fm75** [comment]
@gvdr It might be useful to be able to compare the logs from this time versus last time.

**Comment by gvdr** [comment]
Logs were clean. Due to other issues (traefik conflicting with apache for port 80) I removed everything. I _think_ the difference was in doing a full clean up (as for #128 ) rather than just removing /opt/tljh.

**Comment by fm75** [comment]
@gvdr What was a full clean? I am starting to suspect that pip caching might be an issue that makes removing /opt/tljh not always work.

**Comment by reynoldsnlp** [comment]
I have a solution.

I was having the same issue. I tried the full clean up(TM) (as in #128), and that didn't help.

Finally, I manually `pip uninstall`ed the following: `jupyter-client` `jupyter-core` `jupyterhub` `jupyterhub-systemdspawner`. Installed and running!

Now I just have to figure out why my admin user isn't working.... ;-)

**Comment by fm75** [comment]
@reynoldsnlp  Thanks. That pretty much confirms my theory on this. I have been super-busy, but I think the pip install needs to force install. I want to add that and some additional logging to show the actual output of the commands that are run by install.py.

**Comment by dgot** [comment]
I solved this by installing jupyter and manually copying jupyter into /opt/tljh/user/bin/
`cd /usr/bin`
`sudo cp jupyter /opt/tljh/user/bin/`

**Comment by coreyclip** [comment]
I was able to resolve the issue by also pip uninistalling jupyter as per @reynoldsnlp suggestion. 
I believe my initial jupyter installation that had to be removed came from installing the Anaconda Distribution way back.

**Comment by hMED22** [comment]
I had this problem and solved it like @dgot said but than had another problem launching the server, using `sudo journalctl -u jupyter-<name-of-user>` I found that an Import error was raised for a package that I had installed in my local python environment but not in `/opt/tljh/user/` environment. 
but when I tried to install it:
```
source /opt/tljh/user/bin/activate 
sudo -E /opt/tljh/user/bin/pip install package
```
I got  `Requirement already satisfied: package in /home/username/.local/lib/python3.6/site-packages`,
I believe that that's what happened when the tljh installer called  `conda.ensure_pip_packages`.
Finally the thing that fixed it is using `-H` flag with sudo, so to fix this issue one could call:
```
source /opt/tljh/user/bin/activate 
sudo -EH /opt/tljh/user/bin/pip install jupyter
```

**Comment by allan-ja** [comment]
I had the same problem and I resolved it thanks to @hMED22 solution :+1:

**Comment by jhadjar** [comment]
Thank you, dear colleague : ) This should teach me to read the README.md

**Comment by phcreery** [comment]
@dgot solved the problem for me. 

After the error, ` sudo cp /usr/local/bin/jupyter /opt/tljh/user/bin/` and the retry, install completed.
