### ISSUE TITLE
Cannot upgrade while https is enabled

### ISSUE THREAD

**Issue by minrk** [jupyterhub/the-littlest-jupyterhub#277]
Running `python3 bootstrap.py` on an existing deployment fails with:

```python-traceback
Waiting for JupyterHub to come up (1/4 tries)
Waiting for JupyterHub to come up (2/4 tries)
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 448, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 438, in main
    ensure_jupyterhub_running()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 288, in ensure_jupyterhub_running
    urlopen('http://127.0.0.1')
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>
```

We use `urlopen('http://127.0.0.1')` to check if the hub is up during the install phase. This follows redirects and ssl verification will fail on the resulting `https://127.0.0.1` if https is enabled.

What we should probably do is use `requests.get('http://127.0.0.1', allow_redirects=False)` and consider the 302 redirect response to be a successful indicator that the Hub is up. Alternately, follow redirects and use `verify=False` because we don't care at this level that SSL is valid (it never will be for localhost), only that things are running.

**Comment by yuvipanda** [comment]
setting verify=False with a comment on why seems good to me.

**Comment by miickel** [comment]
I think we've run into a similar (if not same) issue. Our VM crashed and had to restart, which resulted in the upgrade script to run on restart. But it fails with similar errors as @minrk 

```
Mar  8 10:12:29 jhub traefik[2165]: time="2019-03-08T10:12:29Z" level=info msg="Testing certificate renew..."
Mar  8 10:12:29 jhub startup-script: INFO startup-script: Waiting for JupyterHub to come up (2/20 tries)
Mar  8 10:12:29 jhub startup-script: INFO startup-script: Traceback (most recent call last):
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     encode_chunked=req.has_header('Transfer-encoding'))
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/http/client.py", line 1239, in request
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     self._send_request(method, url, body, headers, encode_chunked)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     self.endheaders(body, encode_chunked=encode_chunked)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     self._send_output(message_body, encode_chunked=encode_chunked)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     self.send(msg)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/http/client.py", line 964, in send
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     self.connect()
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/http/client.py", line 1400, in connect
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     server_hostname=server_hostname)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     _context=self, _session=session)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/ssl.py", line 817, in __init__
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     self.do_handshake()
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     self._sslobj.do_handshake()
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     self._sslobj.do_handshake()
Mar  8 10:12:29 jhub startup-script: INFO startup-script: ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)
Mar  8 10:12:29 jhub startup-script: INFO startup-script: During handling of the above exception, another exception occurred:
Mar  8 10:12:29 jhub startup-script: INFO startup-script: Traceback (most recent call last):
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     "__main__", mod_spec)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     exec(code, run_globals)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 453, in <module>
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     main()
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 443, in main
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     ensure_jupyterhub_running()
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 294, in ensure_jupyterhub_running
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     urlopen('http://127.0.0.1')
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     return opener.open(url, data, timeout)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     response = meth(req, response)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     'http', request, response, code, msg, hdrs)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/urllib/request.py", line 564, in error
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     result = self._call_chain(*args)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     result = func(*args)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     return self.parent.open(new, timeout=req.timeout)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/urllib/request.py", line 526, in open
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     response = self._open(req, data)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     '_open', req)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     result = func(*args)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     context=self._context, check_hostname=self._check_hostname)
Mar  8 10:12:29 jhub startup-script: INFO startup-script:   File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
Mar  8 10:12:29 jhub startup-script: INFO startup-script:     raise URLError(err)
Mar  8 10:12:29 jhub startup-script: INFO startup-script: urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>
Mar  8 10:12:29 jhub startup-script: INFO startup-script: checksum mismatch on /opt/tljh/hub/bin/traefik
Mar  8 10:12:29 jhub startup-script: INFO startup-script: Downloading traefik 1.7.5...
Mar  8 10:12:30 jhub startup-script: INFO startup-script: Return code 1.
Mar  8 10:12:30 jhub startup-script: INFO Finished running startup scripts.
```

There is now no way for us to access JupyterHub as we use oauth for authentication and the redirect URL is set to the SSL-enabled endpoint, so even if we can access the page (by removing the startup script from the Compute Engine instance, and accessing it via non-secure HTTP), we cannot sign in anymore.

Is there a temporary fix so we at least can sign in and access our notebooks?

Thanks

**Comment by yuvipanda** [comment]
we're using urllib here, rather than requests. We should probably:

1. Mark requests as an explicit dependency (it comes in as a transient dependency now)
2. Switch from urllib to requests

**Comment by yuvipanda** [comment]
We also have some logic where we don't treat ConnectionRefused errors as failures, and we should probably keep it that way.

**Comment by JuanCab** [comment]
I just got this error while attempting to upgrade TLJH, should the error be present in the current release available via bootstrap.py?

**Comment by yuvipanda** [comment]
@JuanCab merged the PR, so it should be doable.

Thanks to @GeorgianaElena for making this happen!

**Comment by JuanCab** [comment]
I just tried the upgrade and got the following error, which I think is the expected behavior, please confirm!
`/opt/tljh/hub/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)`
If this is OK, you might want to change the error message to suggest testing the https connection, and if it works, things are good.

**Comment by yuvipanda** [comment]
Thanks @JuanCab. Was the upgrade able to continue after this warning? Or did it fail?

**Comment by JuanCab** [comment]
It did appear to finish and is functional.

**Comment by yuvipanda** [comment]
Thanks, @JuanCab. I opened https://github.com/jupyterhub/the-littlest-jupyterhub/issues/356
