### ISSUE TITLE
Automatic HTTPS setting doesn't work

### ISSUE THREAD

**Issue by lucas-mior** [jupyterhub/the-littlest-jupyterhub#345]
I currently have a server running JupyterHub and when I set automatic https with Let's Encrypt and reloaded proxy, and access JupyterHub, it says the certificate is not valid.
My config.yaml:

user:
    admin:
    - xxxxx
https:
    enabled: true
    letsencrypt:
        email: xxxxx@gmail.com
        domains:
        - xxxxxxx

**Comment by lachlancampbell** [comment]
I've had this sporadically as well, but I believe its a LetsEncrypt problem rather than a TLJH problem. Sometimes the domain check just fails, and I haven't been able to figure out why. See below for logs from a previous instance:

May 14 05:01:30 ansible-instance python3[18826]: [E 2019-05-14 05:01:30.204 JupyterHub proxy:102] Error checking traefik api for backend /
May 14 05:01:30 ansible-instance python3[18826]:     Traceback (most recent call last):
May 14 05:01:30 ansible-instance python3[18826]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub_traefik_proxy/proxy.py", line 99, in _check_for_traefik_endpoint
May 14 05:01:30 ansible-instance python3[18826]:         resp = await self._traefik_api_request(path)
May 14 05:01:30 ansible-instance python3[18826]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub_traefik_proxy/proxy.py", line 142, in _traefik_api_request
May 14 05:01:30 ansible-instance python3[18826]:         auth_password=self.traefik_api_password,
May 14 05:01:30 ansible-instance python3[18826]:     ConnectionRefusedError: [Errno 111] Connection refused
...
May 14 05:01:43 ansible-instance traefik[18819]: time="2019-05-14T05:01:43Z" level=error msg="Unable to obtain ACME certificate for domains \"tljh.myddns.rocks\" : unable to generate a certificate for the domains [tljh.myddns.rocks]: acme: Error -> One or more domains had a problem:\n[tljh.myddns.rocks] acme: Error 400 - urn:ietf:params:acme:error:connection - Fetching http://tljh.myddns.rocks/.well-known/acme-challenge/Paf3ua17jTCO4ixn34Oj2oSyriuTeTewOTBv35ts9Tg: Timeout during connect (likely firewall problem)\n"

**Comment by efedorov-dart** [comment]
The same issue.

**Comment by gantheaume** [comment]
I guess that's the same issue:
https://github.com/jupyterhub/the-littlest-jupyterhub/issues/115
