### ISSUE TITLE
Intermittent failure to install when using Ansible playbook

### ISSUE THREAD

**Issue by lachlancampbell** [jupyterhub/the-littlest-jupyterhub#346]
I'm having occasional failures when installing via playbook onto an Openstack VM running Ubuntu 18.04. It may well be the cloud itself, but if anybody has any insight as to why it might be occuring and how to fix, I'd appreciate it.

fatal: [testvm]: FAILED! => changed=true
  cmd: curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo -E python3 - --admin ubuntu
  delta: '0:00:12.192666'
  end: '2019-05-24 03:27:17.743598'
  msg: non-zero return code
  rc: 1
  start: '2019-05-24 03:27:05.550932'
  stderr: |2-
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 44  4346   44  1917    0     0   3826      0  0:00:01 --:--:--  0:00:01  3818100  4346  100  4346    0     0   8555      0 --:--:-- --:--:-- --:--:--  8538
    Checking if TLJH is already installed...
    Setting up hub environment
    Traceback (most recent call last):
      File "<stdin>", line 125, in <module>
      File "<stdin>", line 88, in main
      File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['apt-get', 'install', '--yes', 'python3', 'python3-venv', 'git']' returned non-zero exit status 100.
  stderr_lines:
  - '  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current'
  - '                                 Dload  Upload   Total   Spent    Left  Speed'
  - ''
  - '  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0'
  - ' 44  4346   44  1917    0     0   3826      0  0:00:01 --:--:--  0:00:01  3818'
  - 100  4346  100  4346    0     0   8555      0 --:--:-- --:--:-- --:--:--  8538
  - Checking if TLJH is already installed...
  - Setting up hub environment
  - 'Traceback (most recent call last):'
  - '  File "<stdin>", line 125, in <module>'
  - '  File "<stdin>", line 88, in main'
  - '  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output'
  - '    **kwargs).stdout'
  - '  File "/usr/lib/python3.6/subprocess.py", line 418, in run'
  - '    output=stdout, stderr=stderr)'
  - 'subprocess.CalledProcessError: Command ''[''apt-get'', ''install'', ''--yes'', ''python3'', ''python3-venv'', ''git'']'' returned non-zero exit status 100.'
  stdout: ''
  stdout_lines: <omitted>

**Comment by yuvipanda** [comment]
Once #337 is merged, this should provide you with much more useful output. Does running the failing apt-get command in the VM work?

**Comment by lachlancampbell** [comment]
From memory, yes, running the command manually works fine and so does the entire installation.
