### ISSUE TITLE
server is slow to start then gives timeout error

### ISSUE THREAD

**Issue by lachlancampbell** [jupyterhub/the-littlest-jupyterhub#351]
I'm having problems where if I leave a hub running for an extended period of time (weeks or longer) it becomes slow to respond and sometimes unable to start a user's server, for example:

May 27 03:07:25 littlehub python3[1910]: [I 2019-05-27 03:07:25.408 JupyterHub proxy:301] Checking routes
May 27 03:07:33 littlehub python3[1910]: [W 2019-05-27 03:07:33.210 JupyterHub base:714] User lukeedwards is slow to start (timeout=10)
May 27 03:07:33 littlehub python3[1910]: [I 2019-05-27 03:07:33.212 JupyterHub log:158] 202 POST /hub/api/users/lukeedwards/server (lachlan@106.69.254.220) 10064.93ms
May 27 03:08:02 littlehub python3[1910]: [I 2019-05-27 03:08:02.138 JupyterHub log:158] 200 GET /hub/admin (lachlan@106.69.254.220) 49.57ms
May 27 03:08:23 littlehub python3[1910]: [W 2019-05-27 03:08:23.294 JupyterHub user:471] lukeedwards's server failed to start in 60 seconds, giving up
May 27 03:08:23 littlehub python3[1910]: [E 2019-05-27 03:08:23.380 JupyterHub gen:593] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/handlers/base.py:619> exception=TimeoutError('Timeout',)> after timeout
May 27 03:08:23 littlehub python3[1910]:     Traceback (most recent call last):
May 27 03:08:23 littlehub python3[1910]:       File "/opt/tljh/hub/lib/python3.6/site-packages/tornado/gen.py", line 589, in error_callback
May 27 03:08:23 littlehub python3[1910]:         future.result()
May 27 03:08:23 littlehub python3[1910]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
May 27 03:08:23 littlehub python3[1910]:         await spawn_future
May 27 03:08:23 littlehub python3[1910]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/user.py", line 489, in spawn
May 27 03:08:23 littlehub python3[1910]:         raise e
May 27 03:08:23 littlehub python3[1910]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/user.py", line 409, in spawn
May 27 03:08:23 littlehub python3[1910]:         url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
May 27 03:08:23 littlehub python3[1910]:     tornado.util.TimeoutError: Timeout

I've tried reloading the hub, and restarting the VM (Ubuntu 18.04 on Openstack) with no success.

**Comment by lachlancampbell** [comment]
I also tried deleting the user and creating a new user, but faced the same issues. At this stage I'm going to trash the VM and start again, but I'd like to know a better solution :)

**Comment by lachlancampbell** [comment]
Don't know if it's relevant, but the traefik logs show a lot of the following errors:

        "__CURSOR" : "s=440e4b14ca704e02b779fd869a74565b;i=ea0d0;b=09c8ee45c9134834a058a7078bc785bc;m=4ec0605bad;t=589d59c2ddaee;x=ef952bcfedaec3d7",
        "__REALTIME_TIMESTAMP" : "1558925424843502",
        "__MONOTONIC_TIMESTAMP" : "338234989485",
        "_BOOT_ID" : "09c8ee45c9134834a058a7078bc785bc",
        "PRIORITY" : "6",
        "SYSLOG_FACILITY" : "3",
        "_MACHINE_ID" : "a95e814a37844c22b16c0168297d3050",
        "_HOSTNAME" : "littlehub",
        "_TRANSPORT" : "stdout",
        "_UID" : "0",
        "_GID" : "0",
        "_SELINUX_CONTEXT" : "unconfined\n",
        "_SYSTEMD_SLICE" : "system.slice",
        "SYSLOG_IDENTIFIER" : "traefik",
        "_COMM" : "traefik",
        "_EXE" : "/opt/tljh/hub/bin/traefik",
        "_CMDLINE" : "/opt/tljh/hub/bin/traefik -c /opt/tljh/state/traefik.toml",
        "_CAP_EFFECTIVE" : "3ff7fcffff",
        "_SYSTEMD_CGROUP" : "/system.slice/traefik.service",
        "_SYSTEMD_UNIT" : "traefik.service",
        "_STREAM_ID" : "69f2bb4f58c14dadb0e8bc0a73300da4",
        "_PID" : "1121",
        "_SYSTEMD_INVOCATION_ID" : "0499aef90ffd4afab1e65e84d93e5d84",
        "MESSAGE" : "time=\"2019-05-27T02:50:24Z\" level=error msg=\"Error while closing Hijacked conn: close tcp 192.168.1.13:80->52.63.84.227:48524: use of closed network connection\""

**Comment by dmpe** [comment]
Also facing samilar issues. Hub starts but spawning notebooks leads to the timeout issue

**Comment by arinbasu** [comment]
I installed tljh on a local instance of vultr.com, but several errors:
- I had to install gcc on the instance
- I had to do apt install python3-devel 
Then it installed *something* ending with 'done' message.
When I visited the URL, I could see a login window. 
But on login, it failed to spawn and showed a timeout error.
No notebooks were spawned.

**Comment by lachlancampbell** [comment]
Still being affected by this issue. Started up a new instance, new install, added users, began logging in using user accounts to check server startup. Worked fine for 10, then would timeout. Would work fine again for 5, then timeout again. No traefik errors showing this time, nothing in the users server logs, just the timeout errors in the jupyterhub logs.

**Comment by GeorgianaElena** [comment]
@lachlancampbell, there's a service we added not so long ago that's culling the notebook servers that have been idle for more than 10 min (this is the default value).
If you're using the latest version on master, this might be what's stopping the notebooks.

Checkout [the docs](http://tljh.jupyter.org/en/latest/topic/idle-culler.html) on how to change the idle timeout and other defaults to fit your needs.

**Comment by lachlancampbell** [comment]
Okay, thanks. I'll try turning the culling service off, although would it stop servers from starting up, as that's what is happening?

**Comment by GeorgianaElena** [comment]
@lachlancampbell, no the idle culler shouldn't stop servers from starting up, it just stops them after 10 min of inactivity. The timeout error you're receiving on this fresh install is the same with the one posted in the initial comment? Do you see anything in the logs related to the idle culler?

**Comment by lachlancampbell** [comment]
I believe it's the same error, but I've included a section of the jupyterhub log below. As you can see, the idle culler does appear.


[log.txt](https://github.com/jupyterhub/the-littlest-jupyterhub/files/3419777/log.txt)

**Comment by rikedyp** [comment]
Jul 23 10:00:30 DyalogDemos python3[25943]: [I 2019-07-23 10:00:30.786 JupyterHub log:174] 200 GET /hub/home (dyalog@10.0.60.180) 27.30ms
Jul 23 10:00:32 DyalogDemos python3[25943]: [I 2019-07-23 10:00:32.816 JupyterHub log:174] 200 GET /hub/token (dyalog@10.0.60.180) 34.88ms
Jul 23 10:00:33 DyalogDemos python3[25943]: [I 2019-07-23 10:00:33.588 JupyterHub log:174] 200 GET /hub/admin (dyalog@10.0.60.180) 10.67ms
Jul 23 10:00:36 DyalogDemos python3[25943]: [I 2019-07-23 10:00:36.224 JupyterHub log:174] 200 GET /hub/home (dyalog@10.0.60.180) 13.75ms
Jul 23 10:00:37 DyalogDemos python3[25943]: [I 2019-07-23 10:00:37.335 JupyterHub systemdspawner:217] user:dyalog Unit jupyter-dyalog in a failed state. Resetting state.
Jul 23 10:00:37 DyalogDemos python3[25943]: Running as unit: jupyter-dyalog.service
Jul 23 10:00:38 DyalogDemos python3[25943]: [I 2019-07-23 10:00:38.281 JupyterHub log:174] 302 GET /hub/spawn/dyalog -> /hub/spawn-pending/dyalog (dyalog@10.0.60.180) 1010.83ms
Jul 23 10:00:38 DyalogDemos python3[25943]: [I 2019-07-23 10:00:38.314 JupyterHub pages:303] dyalog is pending spawn
Jul 23 10:00:38 DyalogDemos python3[25943]: [I 2019-07-23 10:00:38.322 JupyterHub log:174] 200 GET /hub/spawn-pending/dyalog (dyalog@10.0.60.180) 18.92ms
Jul 23 10:00:47 DyalogDemos python3[25943]: [W 2019-07-23 10:00:47.280 JupyterHub base:900] User dyalog is slow to start (timeout=10)
Jul 23 10:01:19 DyalogDemos python3[25943]: [W 190723 10:01:19 cull_idle_servers:129] Not culling server dyalog with pending spawn
Jul 23 10:01:19 DyalogDemos python3[25943]: [I 2019-07-23 10:01:19.547 JupyterHub log:174] 200 GET /hub/api/users (cull-idle@127.0.0.1) 12.79ms
Jul 23 10:01:37 DyalogDemos python3[25943]: [W 2019-07-23 10:01:37.318 JupyterHub user:618] dyalog's server failed to start in 60 seconds, giving up
Jul 23 10:01:37 DyalogDemos python3[25943]: [E 2019-07-23 10:01:37.346 JupyterHub gen:599] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn()
Jul 23 10:01:37 DyalogDemos python3[25943]:     Traceback (most recent call last):
Jul 23 10:01:37 DyalogDemos python3[25943]:       File "/opt/tljh/hub/lib/python3.7/site-packages/tornado/gen.py", line 593, in error_callback
Jul 23 10:01:37 DyalogDemos python3[25943]:         future.result()
Jul 23 10:01:37 DyalogDemos python3[25943]:       File "/opt/tljh/hub/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 807, in finish_user_spawn
Jul 23 10:01:37 DyalogDemos python3[25943]:         await spawn_future
Jul 23 10:01:37 DyalogDemos python3[25943]:       File "/opt/tljh/hub/lib/python3.7/site-packages/jupyterhub/user.py", line 642, in spawn
Jul 23 10:01:37 DyalogDemos python3[25943]:         raise e
Jul 23 10:01:37 DyalogDemos python3[25943]:       File "/opt/tljh/hub/lib/python3.7/site-packages/jupyterhub/user.py", line 546, in spawn
Jul 23 10:01:37 DyalogDemos python3[25943]:         url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
Jul 23 10:01:37 DyalogDemos python3[25943]:     tornado.util.TimeoutError: Timeout
Jul 23 10:01:37 DyalogDemos python3[25943]:     
Jul 23 10:01:37 DyalogDemos python3[25943]: [I 2019-07-23 10:01:37.348 JupyterHub log:174] 200 GET /hub/api/users/dyalog/server/progress (dyalog@10.0.60.180) 58827.07ms
Jul 23 10:02:19 DyalogDemos python3[25943]: [I 2019-07-23 10:02:19.544 JupyterHub log:174] 200 GET /hub/api/users (cull-idle@127.0.0.1) 10.43ms
Jul 23 10:02:52 DyalogDemos python3[25943]: [I 2019-07-23 10:02:52.167 JupyterHub log:174] 302 GET / -> /hub/ (@127.0.0.1) 0.65ms
Jul 23 10:02:52 DyalogDemos python3[25943]: [I 2019-07-23 10:02:52.188 JupyterHub log:174] 302 GET /hub/ -> /hub/login (@127.0.0.1) 0.58ms
Jul 23 10:02:52 DyalogDemos python3[25943]: [I 2019-07-23 10:02:52.236 JupyterHub log:174] 200 GET /hub/login (@127.0.0.1) 17.13ms
Jul 23 10:02:56 DyalogDemos python3[25943]: [I 2019-07-23 10:02:56.403 JupyterHub base:663] User logged in: dyalog
Jul 23 10:02:56 DyalogDemos python3[25943]: [I 2019-07-23 10:02:56.409 JupyterHub log:174] 302 POST /hub/login?next= -> /hub/spawn (dyalog@127.0.0.1) 308.13ms
Jul 23 10:02:56 DyalogDemos python3[25943]: [I 2019-07-23 10:02:56.477 JupyterHub systemdspawner:217] user:dyalog Unit jupyter-dyalog in a failed state. Resetting state.
Jul 23 10:02:56 DyalogDemos python3[25943]: Running as unit: jupyter-dyalog.service
Jul 23 10:02:57 DyalogDemos python3[25943]: [I 2019-07-23 10:02:57.435 JupyterHub log:174] 302 GET /hub/spawn -> /hub/spawn-pending/dyalog (dyalog@127.0.0.1) 1022.26ms
Jul 23 10:02:57 DyalogDemos python3[25943]: [I 2019-07-23 10:02:57.458 JupyterHub pages:303] dyalog is pending spawn
Jul 23 10:02:57 DyalogDemos python3[25943]: [I 2019-07-23 10:02:57.461 JupyterHub log:174] 200 GET /hub/spawn-pending/dyalog (dyalog@127.0.0.1) 14.52ms
Jul 23 10:03:06 DyalogDemos python3[25943]: [W 2019-07-23 10:03:06.433 JupyterHub base:900] User dyalog is slow to start (timeout=10)

**Comment by minrk** [comment]
@lachlancampbell try checking the logs of the server that failed to show up:


    systemctl -u jupyter-cou000

You might also check for load on the system with `htop` (might require `apt -y install htop`).

What's interesting from the logs is that we see systemd attempting to start the server with:

```
Jul 17 06:56:43 littlehub systemd[1]: Started /bin/bash -c cd /home/jupyter-cou000 && exec jupyterhub-singleuser --port=39851.
```

But no output from that process. I think that's the root, that systemd is actually taking a long time to launch the requested process, or even failing entirely to do so. It's especially strange that this same action succeeds in one second, five minutes later:

```
Jul 17 07:01:29 littlehub systemd[1]: Started /bin/bash -c cd /home/jupyter-cou000 && exec jupyterhub-singleuser --port=52651.
Jul 17 07:01:29 littlehub python3[12245]: Running as unit: jupyter-cou000.service
...
# first output from the started server (note SingleUserNotebookApp):
Jul 17 07:01:30 littlehub bash[12547]: [I 2019-07-17 07:01:30.751 SingleUserNotebookApp extension:168] JupyterLab extension loaded from /opt/tljh/user/lib/python3.6/site-packages/jupyterlab
```

I don't have a good answer yet for what could cause this to take a long time, or perhaps fail altogether. It might be worth checking `systemctl status jupyter-cou000` while a launch that's going to fail is in the middle of trying to start. Or just `systemctl status`. That might shed some light on what's going on, such as exhausting some resources.

Are there other active users when this is happening?

**Comment by lachlancampbell** [comment]
Logs for jupyter-cou000 don't show anything more:
Jul 17 06:56:43 littlehub systemd[1]: Started /bin/bash -c cd /home/jupyter-cou000 && exec jupyterhub-singleuser --port=39851.
Jul 17 06:57:14 littlehub systemd[1]: Stopping /bin/bash -c cd /home/jupyter-cou000 && exec jupyterhub-singleuser --port=39851...
Jul 17 06:57:14 littlehub systemd[1]: Stopped /bin/bash -c cd /home/jupyter-cou000 && exec jupyterhub-singleuser --port=39851.

When this occurred I was the only user, so shouldn't have been that. I'll try and replicate it and check the system status as you suggest. 

It's possible it could be an intermittent problem with our cloud, although since others reported the same issue I was hoping it wasn't that.

**Comment by dwr-psandhu** [comment]
I had the same problems, however when I looked into the logs (/var/log/system...) it seemed like python was failing on import jupyterhub. 

I had to sudo to jupyterhub-admin-user and then run conda init as advised [in the anaconda faq]( 
https://docs.anaconda.com/anaconda/user-guide/faq/#distribution-faq-linux-path)

**Comment by mrwen00** [comment]
I've got the same problem. fixed it by deleting your created account, for example user jupyterhub-admin. Delete it with "sudo userdel jupyterhub-admin". 
After removing the account and create again, it works perfectly.

**Comment by Quinten-gs** [comment]
> 
> 
> I also just found that if I run:
> `systemctl reset-failed`
> it clears out failed services and then TLJH can start a server that wouldn't previously start.

This indeed solved the issue for me. Many thanks @rgaushell 

I caused this issue by opening too many tabs in Jupyterlab which crashed the service.

**Comment by junqfisica** [comment]
My problem is that after a few days running the TLJH the server reaches 100% cpu usage. This causes the server to stop responding.

**Comment by Quinten-gs** [comment]
> 
> 
> I've hit the exact same issue as everyone else here. I can't exactly come up with reproduction steps, but it's something like:
> 
>     * Create a user
> 
>     * Have them open a lot of notebooks (5 or more?)
> 
>     * Leave it for a day or more
> 
>     * Come back and your server is dead
> 
>     * Try to start it
> 
>     * Doesn't start, errors in log about timeouts/tornado, startup taking too long
> 
> 
> I have a workaround I've been using, but would really like to find and/or help you patch a permanent solution. If someone can point me at the code that is breaking, I have a team of engineers who would happily submit a PR.
> 
> Workaround:
> 
> ```
> sudo bash
> systemctl stop jupyter-username.service
> systemctl start jupyter-username.service
> ```
> 
> Environment: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-1027-aws x86_64)
> hub: Python 3.6.8 (default, Jan 14 2019, 11:02:34)
> user: Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)

Many thanks @rgaushell , this solved the issue for me.
