### ISSUE TITLE
Jupyter Hub doesn't start if auth state is enabled

### ISSUE THREAD

**Issue by jmartinc89** [jupyterhub/the-littlest-jupyterhub#361]
I'm trying to make auth state persistent in order to provide the access token to the spawner.
I'm using OIDC as authentication protocol, using GenericOAuthAuthenticator.
Login works good.

I'm using a custom jupyterhub_config.py script that contains only:
c.Authenticator.enable_auth_state = True
The script was placed on /opt/tljh/config/jupyterhub_config.d folder

The jupyterhub log shows an error in configuration:
Jun 03 15:24:27 ip-10-11-0-183 python3[1641]: future: <Task finished coro=<JupyterHub.launch_instance_async() done, defined at /opt/tljh/hub/lib/python
Jun 03 15:24:27 ip-10-11-0-183 python3[1641]: Traceback (most recent call last):
Jun 03 15:24:27 ip-10-11-0-183 python3[1641]:   File "/opt/tljh/hub/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
Jun 03 15:24:27 ip-10-11-0-183 python3[1641]:     value = obj._trait_values[self.name]
Jun 03 15:24:27 ip-10-11-0-183 python3[1641]: KeyError: 'config'
I've reproduced the same behavior also by setting enable_auth_state with default value True in a custom authenticator.

**Comment by ChristianKuhre** [comment]
I also have problems with c.Authenticator.enable_auth_state = True

I just get a general error in the jupyterhub logs
> [E 2020-07-03 14:37:41.667 JupyterHub app:2718]
>     Traceback (most recent call last):
>       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/app.py", line 2715, in launch_instance_async
>         await self.initialize(argv)
>       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/app.py", line 2286, in initialize
>         await self.init_users()
>       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/app.py", line 1600, in init_users
>         ck = crypto.CryptKeeper.instance()
>       File "/opt/tljh/hub/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
>         inst = cls(*args, **kwargs)
>       File "/opt/tljh/hub/lib/python3.6/site-packages/traitlets/config/configurable.py", line 87, in __init__
>         self._load_config(self.config)
>       File "/opt/tljh/hub/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
>         return self.get(obj, cls)
>       File "/opt/tljh/hub/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
>         value = self._validate(obj, dynamic_default())
>       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/crypto.py", line 100, in _config_default
>         return JupyterHub.instance().config
>       File "/opt/tljh/hub/lib/python3.6/site-packages/traitlets/config/configurable.py", line 423, in instance
>         '%s are being created.' % cls.__name__
>     traitlets.config.configurable.MultipleInstanceError: Multiple incompatible subclass instances of JupyterHub are being created.

**Comment by danlester** [comment]
@ChristianKuhre I also saw a similar problem. It was down to the way in which JupyterHub was launched.

If I ran `jupyterhub -f <config file>` from the command line, everything was fine.

If I ran `python -m jupyterhub.app -f <config file>` (or something similar - e.g. attempting to run a debug session from the IDE) then I saw the MultipleInstanceError.

The reason is that JupyterHub is first created as a `__main__.JupyterHub` but then a CryptKeeper class in JupyterHub tries to import as `from .app import JupyterHub`. So its class is known as `jupyterhub.app.JupyterHub`. The JupyterHub class is supposed to be a singleton, and it objects to returning the existing JH object because it looks different (jupyterhub.app.JupyterHub versus __main__.JupyterHub).

**Comment by danlester** [comment]
I'm not too sure how to fix this. There may be a better way to invoke JH from the IDE, maybe CryptKeeper needs to do something different, or maybe this [check in traitlets](https://github.com/ipython/traitlets/blob/24fdc2974df20a07b0df9fe499d61bed46783782/traitlets/config/configurable.py#L516) is too strict.

**Comment by cgawron** [comment]
I think this issue is due to the following check in app.py:
```Python
        if self.authenticator.enable_auth_state:
            ck = crypto.CryptKeeper.instance()
            try:
                ck.check_available()
            except Exception as e:
               self.exit(
                    "auth_state is enabled, but encryption is not available: %s" % e
                )
```

If I comment this out, setting `enable_auth_state` works.

**Comment by cgawron** [comment]
Sorry, I was too optimistic – now the server starts, but an exception is thrown during authentication:

> Aug 17 22:10:44 jupiter python3[1148531]:     Traceback (most recent call last):

> Aug 17 22:10:44 jupiter python3[1148531]:       File "/opt/tljh/hub/lib/python3.8/site-packages/tornado/web.py", line 1703, in _execute
> Aug 17 22:10:44 jupiter python3[1148531]:         result = await result
> Aug 17 22:10:44 jupiter python3[1148531]:       File "/opt/tljh/hub/lib/python3.8/site-packages/ltiauthenticator/__init__.py", line 250, in post
> Aug 17 22:10:44 jupiter python3[1148531]:         _ = yield self.login_user()
> Aug 17 22:10:44 jupiter python3[1148531]:       File "/opt/tljh/hub/lib/python3.8/site-packages/jupyterhub/handlers/base.py", line 703, in login_user
> Aug 17 22:10:44 jupiter python3[1148531]:         user = await self.auth_to_user(authenticated)
> Aug 17 22:10:44 jupiter python3[1148531]:       File "/opt/tljh/hub/lib/python3.8/site-packages/jupyterhub/handlers/base.py", line 693, in auth_to_user
> Aug 17 22:10:44 jupiter python3[1148531]:         await user.save_auth_state(auth_state)
> Aug 17 22:10:44 jupiter python3[1148531]:       File "/opt/tljh/hub/lib/python3.8/site-packages/jupyterhub/user.py", line 185, in save_auth_state
> Aug 17 22:10:44 jupiter python3[1148531]:         self.encrypted_auth_state = await encrypt(auth_state)
> Aug 17 22:10:44 jupiter python3[1148531]:       File "/opt/tljh/hub/lib/python3.8/site-packages/jupyterhub/crypto.py", line 171, in encrypt
> Aug 17 22:10:44 jupiter python3[1148531]:         return CryptKeeper.instance().encrypt(data)
> Aug 17 22:10:44 jupiter python3[1148531]:       File "/opt/tljh/hub/lib/python3.8/site-packages/traitlets/config/configurable.py", line 412, in instance
> Aug 17 22:10:44 jupiter python3[1148531]:         inst = cls(*args, **kwargs)
> Aug 17 22:10:44 jupiter python3[1148531]:       File "/opt/tljh/hub/lib/python3.8/site-packages/traitlets/config/configurable.py", line 87, in __init__
> Aug 17 22:10:44 jupiter python3[1148531]:         self._load_config(self.config)
> Aug 17 22:10:44 jupiter python3[1148531]:       File "/opt/tljh/hub/lib/python3.8/site-packages/traitlets/traitlets.py", line 556, in __get__
> Aug 17 22:10:44 jupiter python3[1148531]:         return self.get(obj, cls)
> Aug 17 22:10:44 jupiter python3[1148531]:       File "/opt/tljh/hub/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
> Aug 17 22:10:44 jupiter python3[1148531]:         value = self._validate(obj, dynamic_default())
> Aug 17 22:10:44 jupiter python3[1148531]:       File "/opt/tljh/hub/lib/python3.8/site-packages/jupyterhub/crypto.py", line 100, in _config_default
> Aug 17 22:10:44 jupiter python3[1148531]:         return JupyterHub.instance().config
> Aug 17 22:10:44 jupiter python3[1148531]:       File "/opt/tljh/hub/lib/python3.8/site-packages/traitlets/config/configurable.py", line 421, in instance
> Aug 17 22:10:44 jupiter python3[1148531]:         raise MultipleInstanceError(
> Aug 17 22:10:44 jupiter python3[1148531]:     traitlets.config.configurable.MultipleInstanceError: Multiple incompatible subclass instances of JupyterHub are being created.

**Comment by martinbach** [comment]
I'm also not able to get `auth_state_enabled` to work with a fresh install of TLJH. Following a `tljh-config reload`, the logs also show `MultipleInstanceError`. This seems to be independent of selected Authenticator. Hints towards a working solution for token forwarding in TLJH would be greatly appreciated.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/problems-with-auth-state-persistence-and-token-forwarding-in-tljh/5856/1

**Comment by ScottNotFound** [comment]
I'm using the current workaround and it seems to be working. I modified the import mentioned by @danlester in `crypto.py`.

> The reason is that JupyterHub is first created as a `__main__.JupyterHub` but then a CryptKeeper class in JupyterHub tries to import as `from .app import JupyterHub`. So its class is known as `jupyterhub.app.JupyterHub`. The JupyterHub class is supposed to be a singleton, and it objects to returning the existing JH object because it looks different (jupyterhub.app.JupyterHub versus **main**.JupyterHub).

```
        try:
            from __main__ import JupyterHub
        except ModuleNotFoundError:
            from .app import JupyterHub
```

If it's run as a python script or module then it should successfully import from main, otherwise it would have the normal path.
