### ISSUE TITLE
Installing on mint

### ISSUE THREAD

**Issue by TheOtherRealm** [jupyterhub/the-littlest-jupyterhub#416]
Is there any way to run The Littlest JupyterHub on mint, as it is basically Ubuntu?  I modified the bootstrap.py file to use ID_LIKE instead of ID on line 71 [ `get_os_release_variable('ID_LIKE')` ] and this started to work until I got an error at:

```
Building wheels for collected packages: psutil
  Building wheel for psutil (setup.py): started
  Building wheel for psutil (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/tljh/user/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3vz7pmfk/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3vz7pmfk/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-tzyz90rv --python-tag cp36
       cwd: /tmp/pip-install-3vz7pmfk/psutil/
  Complete output (56 lines):
  In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/syslimits.h:7:0,
                   from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:34,
                   from /usr/include/linux/ethtool.h:21,
                   from /tmp/tmpjtrxbqhq.c:1:
  /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:194:15: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                 ^~~~~~~~~~
  compilation terminated.

```
Haven't looked into what that that psutil is yet, just thought I would put it out there in case someone has been successful using mint

**Comment by pulponair** [comment]
@TheOtherRealm you are missing the libc-dev header files:
sudo apt install linux-libc-dev
maybe also 
sudo apt install libc6-dev

**Comment by bungernut** [comment]
The Next Error:
```
Checking if TLJH is already installed...
Setting up hub environment
Ran apt-get update --yes with exit code 100
Hit:1 http://la-mirrors.evowise.com/ubuntu bionic InRelease
Hit:2 http://la-mirrors.evowise.com/ubuntu bionic-updates InRelease
Hit:3 http://la-mirrors.evowise.com/ubuntu bionic-backports InRelease
Ign:4 https://deb.nodesource.com/node_10.x tricia InRelease
Ign:5 http://packages.linuxmint.com tricia InRelease
Err:6 https://deb.nodesource.com/node_10.x tricia Release
  404  Not Found [IP: 13.227.76.36 443]
Hit:7 http://packages.linuxmint.com tricia Release
Hit:8 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:10 http://archive.canonical.com/ubuntu bionic InRelease
Reading package lists...
E: The repository 'https://deb.nodesource.com/node_10.x tricia Release' does not have a Release file.

Traceback (most recent call last):
  File "bootstrap.py", line 174, in <module>
    main()
  File "bootstrap.py", line 127, in main
    run_subprocess(['apt-get', 'update', '--yes'])
  File "bootstrap.py", line 56, in run_subprocess
    raise subprocess.CalledProcessError(cmd=cmd, returncode=proc.returncode)
subprocess.CalledProcessError: Command '['apt-get', 'update', '--yes']' returned non-zero exit status 100.
```
