### ISSUE TITLE
Using JupyterLab extensions with TLJH JupyterLab Build suggested

### ISSUE THREAD

**Issue by bhope78** [jupyterhub/the-littlest-jupyterhub#440]
**Hello I am not sure where to go with this now, tried enabling a couple extensions but received a Jupyterlab build error** 

Build Recommended
JupyterLab build is suggested:
@jupyterlab/plotly-extension needs to be included in build

**After an attempting build I get this error:** 

Build Failed
Build failed with 500, please run 'jupyter lab build' on the server for full output

I tried to different build methods with the following errors

**jupyterlab build**
Message: 'Error in rmtree'
Arguments: ()
An error occured.
FileExistsError: [Errno 17] File exists: '/opt/tljh/user/share/jupyter/lab/staging'
See the log file for details:  /tmp/jupyterlab-debug-xcu1cdjw.log

/opt/tljh/user/share/jupyter/lab/staging$
build  index.js  linked_packages  node_modules  package.json  templates  webpack.config.js  webpack.prod.config.js  yarn.js  yarn.lock

[LabBuildApp] Building in /opt/tljh/user/share/jupyter/lab
[LabBuildApp] Node v12.8.1

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/labapp.py", line 96, in start
    core_config=self.core_config)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/commands.py", line 378, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/commands.py", line 564, in build
    clean=clean_staging

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/commands.py", line 1010, in _populate_staging
    os.makedirs(staging)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)

[LabBuildApp] FileExistsError: [Errno 17] File exists: '/opt/tljh/user/share/jupyter/lab/staging'

[LabBuildApp] Exiting application: JupyterLab

**jupyterlab-build**
output
Message: 'Error in rmtree'
Arguments: ()
An error occured.
FileExistsError: [Errno 17] File exists: '/opt/tljh/user/share/jupyter/lab/staging'
See the log file for details:  /tmp/jupyterlab-debug-3onmje93.log

LabBuildApp] Building in /opt/tljh/user/share/jupyter/lab
[LabBuildApp] Node v12.8.1

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/labapp.py", line 96, in start
    core_config=self.core_config)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/commands.py", line 378, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/commands.py", line 564, in build
    clean=clean_staging

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/commands.py", line 1010, in _populate_staging
    os.makedirs(staging)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)

[LabBuildApp] FileExistsError: [Errno 17] File exists: '/opt/tljh/user/share/jupyter/lab/staging'

[LabBuildApp] Exiting application: JupyterLab
(base) jupyter-bryana@rstudio-ubuntu-s-1vcpu-2gb-sfo2-01:/tmp$ cat /tmp/jupyterlab-debug-3onmje93.log
[LabBuildApp] Building in /opt/tljh/user/share/jupyter/lab
[LabBuildApp] Node v12.8.1

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/labapp.py", line 96, in start
    core_config=self.core_config)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/commands.py", line 378, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/commands.py", line 564, in build
    clean=clean_staging

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterlab/commands.py", line 1010, in _populate_staging
    os.makedirs(staging)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)

[LabBuildApp] FileExistsError: [Errno 17] File exists: '/opt/tljh/user/share/jupyter/lab/staging'

[LabBuildApp] Exiting application: JupyterLab

**Comment by dschofield** [comment]
I'm working through Jupyter Lab extension build issues myself right now, so I'll add details of anything that works for me as I come across them.
What versions of the various Jupyter components do you have?

```
$ sudo pip freeze | grep jupyt
jupyter==1.0.0
jupyter-client==5.3.3
jupyter-console==6.0.0
jupyter-core==4.5.0
jupyterhub==1.0.0
jupyterlab==1.1.4
jupyterlab-server==1.0.6
nteract-on-jupyter==2.0.7
```

**Comment by jerpson** [comment]
I have the similar problem. I cannot install and update extension in jupyterlab. Could you help me?

**Comment by andyadamides** [comment]
Same issue for me 

```
jupyter-client==5.3.1
jupyter-core==4.4.0
jupyter-server-proxy==1.2.0
jupyterhub==1.0.0
jupyterlab==1.2.3
jupyterlab-code-formatter==1.0.2
jupyterlab-dash==0.1.0a3
jupyterlab-git==0.8.1
jupyterlab-server==1.0.6
```

**Comment by calz1** [comment]
On a fresh install from yesterday, I get this same issue but I haven't installed any extensions. I'm warned I need to do a build and then the build fails from the UI or terminal.


_--- Logging error ---
Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.7/shutil.py", line 493, in rmtree
    os.rmdir(path)
PermissionError: [Errno 13] Permission denied: '/opt/tljh/user/share/jupyter/lab/staging'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/opt/tljh/user/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 117, in format
    return super(LevelFormatter, self).format(record)
  File "/opt/tljh/user/lib/python3.7/logging/__init__.py", line 627, in format
    record.exc_text = self.formatException(record.exc_info)
  File "/opt/tljh/user/lib/python3.7/logging/__init__.py", line 577, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "/opt/tljh/user/lib/python3.7/traceback.py", line 104, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/opt/tljh/user/lib/python3.7/traceback.py", line 476, in __init__
    if (exc_value and exc_value.__cause__ is not None
AttributeError: 'str' object has no attribute '__cause__'
Call stack:
  File "/opt/tljh/user/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/opt/tljh/user/lib/python3.7/site-packages/notebook/notebookapp.py", line 1910, in start
    super(NotebookApp, self).start()
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyter_core/application.py", line 259, in start
    self.subapp.start()
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/labapp.py", line 98, in start
    command=command, app_options=app_options)
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/commands.py", line 650, in build
    clean=clean_staging
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/commands.py", line 1095, in _populate_staging
    _rmtree(staging, self.logger)
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/commands.py", line 1814, in _rmtree
    shutil.rmtree(path, onerror=onerror)
  File "/opt/tljh/user/lib/python3.7/shutil.py", line 495, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/commands.py", line 1812, in onerror
    logger.debug('Error in rmtree', exc_info=exc_info)
Message: 'Error in rmtree'
Arguments: ()
An error occured.
FileExistsError: [Errno 17] File exists: '/opt/tljh/user/share/jupyter/lab/staging'
See the log file for details:  /tmp/jupyterlab-debug-kl04yyqa.log_

**Comment by slipb** [comment]
Normally installation by click will not work.you have to install it by CMD line at terminal in Jupyter
Please remenber `sudo -E `before any installation

**Comment by timhuff** [comment]
Thanks @consideRatio. I was aware of the `sudo -E` thing but unaware that `jupyter lab build` was necessary.

**Comment by consideRatio** [comment]
@timhuff note that `jupyter lab build` is only relevant for jupyterlab 2 or jupyterlab 2 specific extensions you have installed.
