### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by ICTSoEasy** [jupyterhub/the-littlest-jupyterhub#444]
I'm trying to install on an existing DO server running 18.10. I am just trying to share some notebooks with a few students, so not worth the £££ of setting up a whole separate droplet.

I'm getting:

Starting TLJH installer...
Setting up admin users
Granting passwordless sudo to JupyterHub admins...
Setting up user environment...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 482, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 465, in main
    ensure_user_environment(args.user_requirements_txt_url)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 249, in ensure_user_environment
    'conda==4.5.8'
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/conda.py", line 109, in ensure_conda_packages
    ] + packages).decode()
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/tljh/user/bin/python', '-m', 'conda', 'install', '-c', 'conda-forge', '--json', '--prefix', '/opt/tljh/user', 'conda==4.5.8']' died with <Signals.SIGKILL: 9>.

**Comment by GeorgianaElena** [comment]
Hi @ICTSoEasy! I'm extremely sorry for the late reply.
The installation fails because there is probably not enough RAM. Checkout [this thread](https://github.com/jupyterhub/the-littlest-jupyterhub/issues/257) for more info.

Recently the integration tests were also failing because of the available memory so the required minimum server RAM was increased to 1GB (see https://github.com/jupyterhub/the-littlest-jupyterhub/pull/479). So, you will need at least 1GB of RAM on your server for TLJH to work properly.
