### ISSUE TITLE
Install issue on Jetstream

### ISSUE THREAD

**Issue by lordivxx** [jupyterhub/the-littlest-jupyterhub#450]
There seems to be an error with the install instructions for TLJH on the Jetstream platform.

The base image on Jetstream will bring up a Jupyter Notebooks instance but not Jupyter Hub.

Adding the post-install script as per instructions produces the following error and will not come up correctly.

curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py \
>   | sudo python3 -^C
forsythc@js-16-157:/opt/tljh$ curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo python3 - --admin chuckf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6354  100  6354    0     0  24068      0 --:--:-- --:--:-- --:--:-- 23977
Checking if TLJH is already installed...
TLJH already installed, upgrading...
Upgrading TLJH installer...
Setup tljh package
Starting TLJH installer...
Setting up admin users
Granting passwordless sudo to JupyterHub admins...
Setting up user environment...
Ran /opt/tljh/user/bin/python -m pip install --no-cache-dir jupyterhub==1.0.0 notebook==5.7.8 jupyterlab==0.35.4 nteract-on-jupyter==2.0.7 nbgitpuller==0.6.1 nbresuse==0.3.0 ipywidgets==7.4.2 tornado<6.0 with exit code 1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Could not find a version that satisfies the requirement jupyterhub==1.0.0 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.6.1, 0.7.0b1, 0.7.0, 0.7.1, 0.7.2)
ERROR: No matching distribution found for jupyterhub==1.0.0

Traceback (most recent call last):
  File "/opt/tljh/hub/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/tljh/hub/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 482, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 465, in main
    ensure_user_environment(args.user_requirements_txt_url)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 266, in ensure_user_environment
    'tornado<6.0',
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/conda.py", line 135, in ensure_pip_packages
    ] + packages)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/utils.py", line 28, in run_subprocess
    raise subprocess.CalledProcessError(cmd=cmd, returncode=proc.returncode)
subprocess.CalledProcessError: Command '['/opt/tljh/user/bin/python', '-m', 'pip', 'install', '--no-cache-dir', 'jupyterhub==1.0.0', 'notebook==5.7.8', 'jupyterlab==0.35.4', 'nteract-on-jupyter==2.0.7', 'nbgitpuller==0.6.1', 'nbresuse==0.3.0', 'ipywidgets==7.4.2', 'tornado<6.0']' returned non-zero exit status 1.

Please advise as this will be very usefully for some faculty here at UCR.

**Comment by fomightez** [comment]
Have you tried with any other offered images that have Ubuntu 18.04? Those warnings about pip not being able to choose a version that matches the requirement of 1.0.0, makes me think something with the image you are using is outdated. According to [here](https://jupyterhub.readthedocs.io/en/0.7.2/changelog.html) JupyterHub 0.7.2 dates back to 2017.

Unfortunately, I don't have a Jetstream account directly to test myself with the image shown in the current TLJH documentation, or to look and see if there is another image that looks better suited.  
I tested what had worked for me in the past on CyVerse's Atmosphere and it worked today. According to [here](https://wikihub.berkeley.edu/display/istrit/Jetstream+and+CyVerse+Roadmaps), "CyVerse Atmosphere is an open-source interface for Jetstream that allows researchers to quickly and easily provision their own cloud resources at no cost." I have used the Jetstream instructions in the past, only using a smaller instance, to use CyVerse and it worked then (with a possible minor hiccup) and just worked again, with same minor hiccup. Hiccup is not related to what you are seeing though. The image I am using on Cyverse reports:
```text
Updated to 18.04.2 on 3/1/2019
```
