### ISSUE TITLE
Installation stops with error message

### ISSUE THREAD

**Issue by alex9434** [jupyterhub/the-littlest-jupyterhub#496]
Checking if TLJH is already installed...
TLJH already installed, upgrading...
Upgrading TLJH installer...
Ran /opt/tljh/hub/bin/pip install --upgrade git+https://github.com/jupyterhub/the-littlest-jupyterhub.git with exit code 1
Collecting git+https://github.com/jupyterhub/the-littlest-jupyterhub.git
  Cloning https://github.com/jupyterhub/the-littlest-jupyterhub.git to /tmp/pip-zj3csym8-build
Collecting backoff (from the-littlest-jupyterhub==0.1)
  Using cached https://files.pythonhosted.org/packages/f0/32/c5dd4f4b0746e9ec05ace2a5045c1fc375ae67ee94355344ad6c7005fd87/backoff-1.10.0-py2.py3-none-any.whl
Collecting bcrypt (from the-littlest-jupyterhub==0.1)
  Using cached https://files.pythonhosted.org/packages/8b/1d/82826443777dd4a624e38a08957b975e75df859b381ae302cfd7a30783ed/bcrypt-3.1.7-cp34-abi3-manylinux1_x86_64.whl
Collecting jinja2 (from the-littlest-jupyterhub==0.1)
  Using cached https://files.pythonhosted.org/packages/7b/af/b9ed1959cb4bb7332e2b0797476c878fa38d200bfcfe38c6d53517c29bdf/Jinja2-2.11.0-py2.py3-none-any.whl
Collecting jupyterhub-traefik-proxy==0.1.* (from the-littlest-jupyterhub==0.1)
  Could not find a version that satisfies the requirement jupyterhub-traefik-proxy==0.1.* (from the-littlest-jupyterhub==0.1) (from versions: )
No matching distribution found for jupyterhub-traefik-proxy==0.1.* (from the-littlest-jupyterhub==0.1)

Traceback (most recent call last):
  File "bootstrap.py", line 174, in <module>
    main()
  File "bootstrap.py", line 159, in main
    ] + pip_flags + [tljh_repo_path])
  File "bootstrap.py", line 56, in run_subprocess
    raise subprocess.CalledProcessError(cmd=cmd, returncode=proc.returncode)
subprocess.CalledProcessError: Command '['/opt/tljh/hub/bin/pip', 'install', '--upgrade', 'git+https://github.com/jupyterhub/the-littlest-jupyterhub.git']' returned non-zero exit status 1

**Comment by yuvipanda** [comment]
Thanks for reporting this! Can you run the script again? Or even just recreate the VM? I definitely see a matching package [here](https://pypi.org/project/jupyterhub-traefik-proxy/) so I'm not sure why this error.
