### ISSUE TITLE
Install terminates with an error on ubuntu 18.04 server on raspberry pi

### ISSUE THREAD

**Issue by jameshope87** [jupyterhub/the-littlest-jupyterhub#509]
I am not sure how to get the whole bash output, it seems to produce an empty file when I try, but here is the last few lines before exiting:

```
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-armv7l-3.6
    creating build/temp.linux-armv7l-3.6/c
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/opt/tljh/hub/include -I/usr/include/python3.6m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.6/c/_cffi_backend.o
    c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
              ^~~~~~~
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    ----------------------------------------
Command "/opt/tljh/hub/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-v4ku4e45/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bulbk9kh-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/tljh/hub/include/site/python3.6/cffi" failed with error code 1 in /tmp/pip-build-v4ku4e45/cffi/

Traceback (most recent call last):
  File "bootstrap.py", line 174, in <module>
    main()
  File "bootstrap.py", line 159, in main
    ] + pip_flags + [tljh_repo_path])
  File "bootstrap.py", line 56, in run_subprocess
    raise subprocess.CalledProcessError(cmd=cmd, returncode=proc.returncode)
subprocess.CalledProcessError: Command '['/opt/tljh/hub/bin/pip', 'install', '--upgrade', 'git+https://github.com/jupyterhub/the-littlest-jupyterhub.git']' returned non-zero exit status 1.
```

**Comment by calacuda** [comment]
I have this problem too

**Comment by Kandji94** [comment]
Has anyone found a solution? I have the same problem

**Comment by kcjennin** [comment]
Still an issue, same problem on an RPI

**Comment by psychemedia** [comment]
See https://github.com/jupyterhub/the-littlest-jupyterhub/issues/62 for the latest progress on installing TLJH onto arm based processors.
