### ISSUE TITLE
Installation failure on fresh Ubuntu 18.04

### ISSUE THREAD

**Issue by drjarno** [jupyterhub/the-littlest-jupyterhub#526]
I created a fresh VM with 18.04 and ran apt full-upgrade to install the latest updates.

Then I tried to install Jupyter Hub by following the installation instructions:
sudo apt install python3 python3-dev git curl

    curl https://raw.githubusercontent.com/jupyterhub/the-littlest- 
    jupyterhub/master/bootstrap/bootstrap.py | sudo -E python3 - --admin jarno

Unfortunately, this failed with the following error:

      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  6354  100  6354    0     0  38277      0 --:--:-- --:--:-- --:--:-- 38277
    Checking if TLJH is already installed...
    Setting up hub environment
    Installed python & virtual environment
    Set up hub virtual environment
    Setting up TLJH installer...
    Setup tljh package
    Starting TLJH installer...
    Setting up admin users
    Granting passwordless sudo to JupyterHub admins...
    Setting up user environment...
    Downloading & setting up user environment...
    Traceback (most recent call last):
      File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 508, in <module>
        main()
      File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 491, in main
        ensure_user_environment(args.user_requirements_txt_url)
      File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 272, in 
    ensure_user_environment
        'conda==' + conda_version
      File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/conda.py", line 109, in 
    ensure_conda_packages
        ] + packages).decode()
      File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['/opt/tljh/user/bin/python', '-m', 'conda', 'install', '-c', 
    'conda-forge', '--json', '--prefix', '/opt/tljh/user', 'conda==4.8.1']' returned non-zero exit status 1.

I noticed that conda was only at version 4.7.10, so I updated with

    sudo -E /opt/tljh/user/bin/python -m conda update --all

After that, I ran the install command again and this time it worked. I hope this workaround will help you to figure out why the install scripts fails on a fresh Ubuntu 18.04 VM.

**Comment by nmvega** [comment]
@drjarno  I had the same issue, but the cause was different. When you happen to install `conda` (in my case `Miniconda3`, it interferes with the `TLJH` installer. That's because, although parts of the installer does indeed use it's `internal virtual environment python` -- i.e. `/opt/tljh/user/bin/python` -- as that installer downloads additional components to installs them, if it happens to find your external `conda` (i.e. find it first in the `PATH`), then it will cause conflict and crash **exactly** as above.

I ended up removing `conda` completely (100%) and am using straight `python` to intall `TLJH` until I can figure out how to get the `TLJH` installer to reliably work with `conda` installed side-by-side.

P.S. I tried @drjarno update solution, but the failure remained because it kept finding my `conda`'s python.

I hope this helps, too.

**Comment by ltoop** [comment]
I had the error when installing on a Multipass default instance of Ubuntu LTS, with only 1GB memory. Running the command showed an error because that was not enough memory. Failed when 2GB available as well - worked at 4GB.
