### ISSUE TITLE
Conda version error in running bootstrap.py

### ISSUE THREAD

**Issue by thatmushroom** [jupyterhub/the-littlest-jupyterhub#592]
### Bug description
I have a similar setup as referenced here (google cloud, following the instructions, using tljh for about a year, and with daily shutoffs), and am experiencing the same conda issue.
[CondaUpgradeError_Issue517](https://github.com/jupyterhub/the-littlest-jupyterhub/issues/517)  (GCP)

After booting up the compute instance, tljh shows "Bad Gateway" when I go to the URL.

Manually running the bootstrap command below gives the following error:
`curl https://tljh.jupyter.org/bootstrap.py \
  | sudo python3 - \
    --admin chris `

`subprocess.CalledProcessError: Command '['/opt/tljh/user/bin/python', '-m', 'conda', 'install', '-c', 'conda-forge'
, '--json', '--prefix', '/opt/tljh/user', 'conda==4.5.8']' returned non-zero exit status 1.`

Joining that command and running it gives this output: 
`  "caused_by": "None",
  "error": "CondaUpgradeError: This environment has previously been operated on by a conda version that's newer\nth
an the conda currently being used. A newer version of conda is required.\n  target environment location: /opt/tljh/
user\n  current conda version: 4.5.8\n  minimum conda version: 4.7\n",
`

Probably unrelated, the curl command here returns an empty result:
`curl https://tljh.jupyter.org/bootstrap.py \
  | sudo python3 - \
    --admin chris `

**Comment by ikhoury** [comment]
Regarding the curl command, you need to add a `-L` flag because `https://tljh.jupyter.org/bootstrap.py` redirects to `https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py` and by default `curl` doesn't follow redirects.

I also got an error related to `conda` and I'm unable to bootstrap a TLJH environment. I joined the command and executed `/opt/tljh/user/bin/python -m conda install -c conda-forge --json --prefix /opt/tljh/user conda==4.8.1` manually. It completed with no errors because my conda version is already at `4.8.1`. I ran the script again and the setup completed. I still don't know what's wrong with the script, it was working a week ago as you said.

**Comment by JustinMaxwell** [comment]
I get a very similar error when trying to install on new EC2 instance:
`Checking if TLJH is already installed...
TLJH already installed, upgrading...
Upgrading TLJH installer...
Upgraded pip
Setup tljh package
Starting TLJH installer...
Setting up admin users
Granting passwordless sudo to JupyterHub admins...
Setting up user environment...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 530, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 502, in main
    ensure_user_environment(args.user_requirements_txt_url)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 278, in ensure_user_environment
    'conda==' + conda_version
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/conda.py", line 108, in ensure_conda_packages
    ] + packages).decode()
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/tljh/user/bin/python', '-m', 'conda', 'install', '-c', 'conda-forge', '--json', '--prefix', '/opt/tljh/user', 'conda==4.8.1']' died with <Signals.SIGKILL: 9>.
`
