### ISSUE TITLE
cells does not run, after install TLJH on docker container.

### ISSUE THREAD

**Issue by stevechenzy** [jupyterhub/the-littlest-jupyterhub#645]
## Description of the issue
Following the instructions here: https://tljh.jupyter.org/en/latest/contributing/dev-setup.html
I have successfully installed TLJH in a docker container on both windows 10/Mac. 

visiting http://localhost:12000/, and I can add users, and start a new notebook (Python3). 

### The issue is that: 
`
the cells on the notebook cannot run, shows always [*] state.
`

the issue replicates on Window 10 WSL2.0 and Mac. 

## the packages on admin terminal

```
jupyter-admin@5a17b61c5534:~$ pip freeze
alembic==1.4.3
argon2-cffi==20.1.0
asn1crypto==0.24.0
async-generator==1.10
attrs==20.3.0
backcall==0.2.0
bleach==3.2.1
certifi==2020.12.5
certipy==0.1.3
cffi==1.12.3
chardet==3.0.4
conda==4.8.1
conda-package-handling==1.3.11
cryptography==2.7
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
idna==2.8
importlib-metadata==3.3.0
ipykernel==5.4.2
ipython==7.19.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.18.0
Jinja2==2.11.2
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.7
jupyter-core==4.7.0
jupyter-telemetry==0.1.0
jupyterhub==1.2.2
jupyterlab==2.2.9
jupyterlab-pygments==0.1.2
jupyterlab-server==1.2.0
libarchive-c==2.8
Mako==1.1.3
MarkupSafe==1.1.1
mistune==0.8.4
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.0.8
nbgitpuller==0.9.0
nbresuse==0.3.6
nest-asyncio==1.4.3
notebook==6.1.6
nteract-on-jupyter==2.1.3
oauthlib==3.1.0
packaging==20.8
pamela==1.0.0
pandocfilters==1.4.3
parso==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.9.0
prompt-toolkit==3.0.8
psutil==5.8.0
ptyprocess==0.6.0
pycosat==0.6.3
pycparser==2.19
Pygments==2.7.3
pyOpenSSL==19.0.0
pyparsing==2.4.7
pyrsistent==0.17.3
PySocks==1.7.0
python-dateutil==2.8.1
python-editor==1.0.4
python-json-logger==2.0.1
pyzmq==20.0.0
requests==2.22.0
ruamel-yaml==0.15.46
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.2
Send2Trash==1.5.0
six==1.12.0
SQLAlchemy==1.3.22
terminado==0.9.1
testpath==0.4.4
tornado==5.1.1
tqdm==4.32.1
traitlets==5.0.5
typing-extensions==3.7.4.3
urllib3==1.24.2
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
zipp==3.4.0
jupyter-admin@5a17b61c5534:~$
```

### the user log file shows errors

```
jupyter-admin@5a17b61c5534:~$ sudo journalctl -u jupyter-admin
-- Logs begin at Sat 2020-12-26 02:46:38 UTC, end at Sat 2020-12-26 03:15:03 UTC. --
Dec 26 03:09:47 5a17b61c5534 systemd[1]: Started /bin/bash -c cd /home/jupyter-admin && exec jupyterhub-singleuser --port=6
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:50.740 SingleUserNotebookApp extension:162] JupyterLab extensi
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:50.740 SingleUserNotebookApp extension:163] JupyterLab applica
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:50.785 SingleUserNotebookApp extension:22] nteract extension l
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:50.788 SingleUserNotebookApp mixins:558] Starting jupyterhub-s
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:50.803 SingleUserNotebookApp log:181] 302 GET /user/admin/ ->
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [W 2020-12-26 03:09:50.819 SingleUserNotebookApp _version:73] jupyterhub version 1
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:50.819 SingleUserNotebookApp notebookapp:2257] Serving noteboo
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:50.820 SingleUserNotebookApp notebookapp:2257] Jupyter Noteboo
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:50.821 SingleUserNotebookApp notebookapp:2257] http://127.0.0.
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:50.822 SingleUserNotebookApp notebookapp:2258] Use Control-C t
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:50.836 SingleUserNotebookApp mixins:539] Updating Hub with act
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:50.926 SingleUserNotebookApp log:181] 302 GET /user/admin/ ->
Dec 26 03:09:50 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:50.949 SingleUserNotebookApp log:181] 302 GET /user/admin/tree
Dec 26 03:09:51 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:51.135 SingleUserNotebookApp auth:985] Logged-in user {'kind':
Dec 26 03:09:51 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:51.140 SingleUserNotebookApp log:181] 302 GET /user/admin/oaut
Dec 26 03:09:51 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:51.286 SingleUserNotebookApp log:181] 200 GET /user/admin/tree
Dec 26 03:09:51 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:51.762 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:09:51 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:51.790 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:09:51 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:51.799 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:09:51 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:51.803 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:09:51 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:51.826 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:09:51 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:51.834 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:09:51 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:51.861 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:09:56 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:56.234 SingleUserNotebookApp handlers:153] Creating new notebo
Dec 26 03:09:56 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:56.268 SingleUserNotebookApp sign:396] Writing notebook-signin
Dec 26 03:09:56 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:56.299 SingleUserNotebookApp log:181] 201 POST /user/admin/api
Dec 26 03:09:57 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:57.302 SingleUserNotebookApp log:181] 200 GET /user/admin/note
Dec 26 03:09:57 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:57.978 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:09:57 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:57.989 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:09:58 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:58.135 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:09:58 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:58.463 SingleUserNotebookApp kernelmanager:179] Kernel started
Dec 26 03:09:58 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:58.480 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:09:58 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:58.489 SingleUserNotebookApp log:181] 201 POST /user/admin/api
Dec 26 03:09:58 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:58.498 SingleUserNotebookApp log:181] 200 GET /user/admin/metr
Dec 26 03:09:59 5a17b61c5534 bash[5257]: [I 2020-12-26 03:09:59.297 SingleUserNotebookApp log:181] 101 GET /user/admin/api/
Dec 26 03:09:59 5a17b61c5534 bash[5257]: [E 2020-12-26 03:09:59.310 SingleUserNotebookApp ioloop:801] Exception in callback
Dec 26 03:09:59 5a17b61c5534 bash[5257]:     Traceback (most recent call last):
Dec 26 03:09:59 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/ioloop.py", line 75
Dec 26 03:09:59 5a17b61c5534 bash[5257]:         ret = callback()
Dec 26 03:09:59 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/stack_context.py",
Dec 26 03:09:59 5a17b61c5534 bash[5257]:         return fn(*args, **kwargs)
Dec 26 03:09:59 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/notebook/services/kernels/h
Dec 26 03:09:59 5a17b61c5534 bash[5257]:         if self.ws_connection is None or self.ws_connection.is_closing():
Dec 26 03:09:59 5a17b61c5534 bash[5257]:     AttributeError: 'WebSocketProtocol13' object has no attribute 'is_closing'
Dec 26 03:10:03 5a17b61c5534 bash[5257]: [I 2020-12-26 03:10:03.410 SingleUserNotebookApp log:181] 200 GET /user/admin/metr
Dec 26 03:10:28 5a17b61c5534 bash[5257]: [I 2020-12-26 03:10:28.669 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:10:28 5a17b61c5534 bash[5257]: [I 2020-12-26 03:10:28.675 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:10:28 5a17b61c5534 bash[5257]: [I 2020-12-26 03:10:28.704 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:10:36 5a17b61c5534 bash[5257]: [I 2020-12-26 03:10:36.643 SingleUserNotebookApp management:338] New terminal with
Dec 26 03:10:36 5a17b61c5534 bash[5257]: [I 2020-12-26 03:10:36.648 SingleUserNotebookApp log:181] 200 POST /user/admin/api
Dec 26 03:10:36 5a17b61c5534 bash[5257]: [I 2020-12-26 03:10:36.747 SingleUserNotebookApp log:181] 200 GET /user/admin/term
Dec 26 03:10:37 5a17b61c5534 bash[5257]: [I 2020-12-26 03:10:37.457 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:10:37 5a17b61c5534 bash[5257]: [I 2020-12-26 03:10:37.480 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:10:37 5a17b61c5534 bash[5257]: [I 2020-12-26 03:10:37.502 SingleUserNotebookApp log:181] 101 GET /user/admin/term
Dec 26 03:10:37 5a17b61c5534 bash[5257]: TermSocket.open: 1
Dec 26 03:10:37 5a17b61c5534 bash[5257]: TermSocket.open: Opened 1
Dec 26 03:10:59 5a17b61c5534 bash[5257]: [E 2020-12-26 03:10:59.271 SingleUserNotebookApp ioloop:801] Exception in callback
Dec 26 03:10:59 5a17b61c5534 bash[5257]:     Traceback (most recent call last):
Dec 26 03:10:59 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/ioloop.py", line 75
Dec 26 03:10:59 5a17b61c5534 bash[5257]:         ret = callback()
Dec 26 03:10:59 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/stack_context.py",
Dec 26 03:10:59 5a17b61c5534 bash[5257]:         return fn(*args, **kwargs)
Dec 26 03:10:59 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/websocket.py", line
Dec 26 03:10:59 5a17b61c5534 bash[5257]:         self.stream.io_loop.add_future(result, lambda f: f.result())
Dec 26 03:10:59 5a17b61c5534 bash[5257]:     tornado.util.TimeoutError: Timeout
Dec 26 03:10:59 5a17b61c5534 bash[5257]: Future exception was never retrieved
Dec 26 03:10:59 5a17b61c5534 bash[5257]: future: <Future finished exception=TimeoutError('Timeout')>
Dec 26 03:10:59 5a17b61c5534 bash[5257]: Traceback (most recent call last):
Dec 26 03:10:59 5a17b61c5534 bash[5257]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 1141, in
Dec 26 03:10:59 5a17b61c5534 bash[5257]:     yielded = self.gen.throw(*exc_info)
Dec 26 03:10:59 5a17b61c5534 bash[5257]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/websocket.py", line 757
Dec 26 03:10:59 5a17b61c5534 bash[5257]:     yield open_result
Dec 26 03:10:59 5a17b61c5534 bash[5257]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 1133, in
Dec 26 03:10:59 5a17b61c5534 bash[5257]:     value = future.result()
Dec 26 03:10:59 5a17b61c5534 bash[5257]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/ioloop.py", line 758, i
Dec 26 03:10:59 5a17b61c5534 bash[5257]:     ret = callback()
Dec 26 03:10:59 5a17b61c5534 bash[5257]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/stack_context.py", line
Dec 26 03:10:59 5a17b61c5534 bash[5257]:     return fn(*args, **kwargs)
Dec 26 03:10:59 5a17b61c5534 bash[5257]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/websocket.py", line 553
Dec 26 03:10:59 5a17b61c5534 bash[5257]:     self.stream.io_loop.add_future(result, lambda f: f.result())
Dec 26 03:10:59 5a17b61c5534 bash[5257]: tornado.util.TimeoutError: Timeout
Dec 26 03:11:58 5a17b61c5534 bash[5257]: [I 2020-12-26 03:11:58.867 SingleUserNotebookApp log:181] 200 GET /user/admin/api/
Dec 26 03:11:58 5a17b61c5534 bash[5257]: [I 2020-12-26 03:11:58.878 SingleUserNotebookApp handlers:164] Saving file at /Unt
Dec 26 03:11:58 5a17b61c5534 bash[5257]: [I 2020-12-26 03:11:58.892 SingleUserNotebookApp log:181] 200 PUT /user/admin/api/
Dec 26 03:11:59 5a17b61c5534 bash[5257]: [W 2020-12-26 03:11:59.279 SingleUserNotebookApp zmqhandlers:179] WebSocket ping t
Dec 26 03:12:00 5a17b61c5534 bash[5257]: [W 2020-12-26 03:12:00.855 SingleUserNotebookApp handlers:366] Replacing stale con
Dec 26 03:12:04 5a17b61c5534 bash[5257]: [I 2020-12-26 03:12:04.285 SingleUserNotebookApp kernelmanager:222] Starting buffe
Dec 26 03:12:04 5a17b61c5534 bash[5257]: [I 2020-12-26 03:12:04.289 SingleUserNotebookApp log:181] 101 GET /user/admin/api/
Dec 26 03:12:04 5a17b61c5534 bash[5257]: [I 2020-12-26 03:12:04.290 SingleUserNotebookApp handlers:378] Restoring connectio
Dec 26 03:12:04 5a17b61c5534 bash[5257]: [E 2020-12-26 03:12:04.292 SingleUserNotebookApp ioloop:801] Exception in callback
Dec 26 03:12:04 5a17b61c5534 bash[5257]:     Traceback (most recent call last):
Dec 26 03:12:04 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/ioloop.py", line 75
Dec 26 03:12:04 5a17b61c5534 bash[5257]:         ret = callback()
Dec 26 03:12:04 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/stack_context.py",
Dec 26 03:12:04 5a17b61c5534 bash[5257]:         return fn(*args, **kwargs)
Dec 26 03:12:04 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/notebook/services/kernels/h
Dec 26 03:12:04 5a17b61c5534 bash[5257]:         if self.ws_connection is None or self.ws_connection.is_closing():
Dec 26 03:12:04 5a17b61c5534 bash[5257]:     AttributeError: 'WebSocketProtocol13' object has no attribute 'is_closing'
Dec 26 03:13:04 5a17b61c5534 bash[5257]: [E 2020-12-26 03:13:04.250 SingleUserNotebookApp ioloop:801] Exception in callback
Dec 26 03:13:04 5a17b61c5534 bash[5257]:     Traceback (most recent call last):
Dec 26 03:13:04 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/ioloop.py", line 75
Dec 26 03:13:04 5a17b61c5534 bash[5257]:         ret = callback()
Dec 26 03:13:04 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/stack_context.py",
Dec 26 03:13:04 5a17b61c5534 bash[5257]:         return fn(*args, **kwargs)
Dec 26 03:13:04 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/websocket.py", line
Dec 26 03:13:04 5a17b61c5534 bash[5257]:         self.stream.io_loop.add_future(result, lambda f: f.result())
Dec 26 03:13:04 5a17b61c5534 bash[5257]:     tornado.util.TimeoutError: Timeout
Dec 26 03:13:04 5a17b61c5534 bash[5257]: Future exception was never retrieved
Dec 26 03:13:04 5a17b61c5534 bash[5257]: future: <Future finished exception=TimeoutError('Timeout')>
Dec 26 03:13:04 5a17b61c5534 bash[5257]: Traceback (most recent call last):
Dec 26 03:13:04 5a17b61c5534 bash[5257]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 1141, in
Dec 26 03:13:04 5a17b61c5534 bash[5257]:     yielded = self.gen.throw(*exc_info)
Dec 26 03:13:04 5a17b61c5534 bash[5257]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/websocket.py", line 757
Dec 26 03:13:04 5a17b61c5534 bash[5257]:     yield open_result
Dec 26 03:13:04 5a17b61c5534 bash[5257]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 1133, in
Dec 26 03:13:04 5a17b61c5534 bash[5257]:     value = future.result()
Dec 26 03:13:04 5a17b61c5534 bash[5257]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/ioloop.py", line 758, i
Dec 26 03:13:04 5a17b61c5534 bash[5257]:     ret = callback()
Dec 26 03:13:04 5a17b61c5534 bash[5257]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/stack_context.py", line
Dec 26 03:13:04 5a17b61c5534 bash[5257]:     return fn(*args, **kwargs)
Dec 26 03:13:04 5a17b61c5534 bash[5257]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/websocket.py", line 553
Dec 26 03:13:04 5a17b61c5534 bash[5257]:     self.stream.io_loop.add_future(result, lambda f: f.result())
Dec 26 03:13:04 5a17b61c5534 bash[5257]: tornado.util.TimeoutError: Timeout
Dec 26 03:14:04 5a17b61c5534 bash[5257]: [W 2020-12-26 03:14:04.275 SingleUserNotebookApp zmqhandlers:179] WebSocket ping t
Dec 26 03:14:05 5a17b61c5534 bash[5257]: [W 2020-12-26 03:14:05.858 SingleUserNotebookApp handlers:366] Replacing stale con
Dec 26 03:14:09 5a17b61c5534 bash[5257]: [I 2020-12-26 03:14:09.282 SingleUserNotebookApp kernelmanager:222] Starting buffe
Dec 26 03:14:09 5a17b61c5534 bash[5257]: [I 2020-12-26 03:14:09.286 SingleUserNotebookApp log:181] 101 GET /user/admin/api/
Dec 26 03:14:09 5a17b61c5534 bash[5257]: [I 2020-12-26 03:14:09.287 SingleUserNotebookApp handlers:378] Restoring connectio
Dec 26 03:14:09 5a17b61c5534 bash[5257]: [E 2020-12-26 03:14:09.290 SingleUserNotebookApp ioloop:801] Exception in callback
Dec 26 03:14:09 5a17b61c5534 bash[5257]:     Traceback (most recent call last):
Dec 26 03:14:09 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/ioloop.py", line 75
Dec 26 03:14:09 5a17b61c5534 bash[5257]:         ret = callback()
Dec 26 03:14:09 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/stack_context.py",
Dec 26 03:14:09 5a17b61c5534 bash[5257]:         return fn(*args, **kwargs)
Dec 26 03:14:09 5a17b61c5534 bash[5257]:       File "/opt/tljh/user/lib/python3.7/site-packages/notebook/services/kernels/h
Dec 26 03:14:09 5a17b61c5534 bash[5257]:         if self.ws_connection is None or self.ws_connection.is_closing():
Dec 26 03:14:09 5a17b61c5534 bash[5257]:     AttributeError: 'WebSocketProtocol13' object has no attribute 'is_closing'
Dec 26 03:15:03 5a17b61c5534 sudo[5326]: jupyter-admin : TTY=pts/1 ; PWD=/home/jupyter-admin ; USER=root ; COMMAND=/bin/jou
Dec 26 03:15:03 5a17b61c5534 sudo[5326]: pam_env(sudo:session): Unable to open env file: /etc/default/locale: No such file
Dec 26 03:15:03 5a17b61c5534 sudo[5326]: pam_unix(sudo:session): session opened for user root by (uid=0)
```

**Comment by mlline00** [comment]
Looks like there's a breaking change in notebook 6.1.6 installed by the bootstrap script. Reverting to 6.1.5 addressed the issue for me: sudo -E pip install notebook==6.1.5

**Comment by stevechenzy** [comment]
I have tried @milline00's approach. does not work for me. 

in further test on the web admin terminal. I have tried the command: **tljh-config**

shows there is a conflict on python versions. 

by default it load the library from 3.6, have a version conflict on chardet;
```
jupyter-admin@269bfc0d11ed:~$ python3 -V
Python 3.7.3
jupyter-admin@269bfc0d11ed:~$ tljh-config
Traceback (most recent call last):
  File "/opt/tljh/hub/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/opt/tljh/hub/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/tljh/hub/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/opt/tljh/hub/lib/python3.6/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/usr/bin/tljh-config", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/tljh/hub/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/opt/tljh/hub/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/opt/tljh/hub/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/tljh/hub/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/tljh/hub/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/tljh/hub/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/opt/tljh/hub/lib/python3.6/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})
```

if reinstall full the pthon3.7 and rename the 3.6 lib folder. another error:
```
jupyter-admin@269bfc0d11ed:~$ tljh-config
Traceback (most recent call last):
  File "/usr/bin/tljh-config", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

Looks like TLJH current version has not been fully tested. suffering...

**Comment by 6palace** [comment]
+1 we see this too. Thanks for the fix!

**Comment by stevechenzy** [comment]
@GeorgianaElena Thank you very much!

I have just verified, the cells runs well and tljh-config command works fine. 

Great job!

**Comment by GeorgianaElena** [comment]
Thanks a lot for reporting the problem @stevechenzy! <3
