### ISSUE TITLE
Error loading server extension jupyterlab. /lab gives 404

### ISSUE THREAD

**Issue by vivekpradhan** [jupyterhub/the-littlest-jupyterhub#687]
### Bug description

Error loading server extension jupyterlab. /lab gives 404. /tree and /nteract works

### How to reproduce
I installed as per [this](https://tljh.jupyter.org/en/latest/install/custom-server.html) on ubuntu 18.04. 

 ### Output of `sudo journalctl -u jupyter-admin` (the username is admin)
```
Apr 28 01:31:16 ceew-vm systemd[1]: Started /bin/bash -c cd /home/jupyter-admin && exec jupyterhub-singleuser --port=55465.
Apr 28 01:31:17 ceew-vm bash[11665]: [W 2021-04-28 01:31:17.702 SingleUserNotebookApp notebookapp:1950] Error loading server extension jupyterlab
Apr 28 01:31:17 ceew-vm bash[11665]:     Traceback (most recent call last):
Apr 28 01:31:17 ceew-vm bash[11665]:       File "/opt/tljh/user/lib/python3.7/site-packages/notebook/notebookapp.py", line 1942, in init_server_extensions
Apr 28 01:31:17 ceew-vm bash[11665]:         mod = importlib.import_module(modulename)
Apr 28 01:31:17 ceew-vm bash[11665]:       File "/opt/tljh/user/lib/python3.7/importlib/__init__.py", line 127, in import_module
Apr 28 01:31:17 ceew-vm bash[11665]:         return _bootstrap._gcd_import(name[level:], package, level)
Apr 28 01:31:17 ceew-vm bash[11665]:       File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Apr 28 01:31:17 ceew-vm bash[11665]:       File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Apr 28 01:31:17 ceew-vm bash[11665]:       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
Apr 28 01:31:17 ceew-vm bash[11665]:       File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
Apr 28 01:31:17 ceew-vm bash[11665]:       File "<frozen importlib._bootstrap_external>", line 728, in exec_module
Apr 28 01:31:17 ceew-vm bash[11665]:       File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Apr 28 01:31:17 ceew-vm bash[11665]:       File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/__init__.py", line 7, in <module>
Apr 28 01:31:17 ceew-vm bash[11665]:         from .labapp import LabApp
Apr 28 01:31:17 ceew-vm bash[11665]:       File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/labapp.py", line 15, in <module>
Apr 28 01:31:17 ceew-vm bash[11665]:         from jupyterlab_server import slugify, WORKSPACE_EXTENSION
Apr 28 01:31:17 ceew-vm bash[11665]:       File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
Apr 28 01:31:17 ceew-vm bash[11665]:         from .app import LabServerApp
Apr 28 01:31:17 ceew-vm bash[11665]:       File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab_server/app.py", line 7, in <module>
Apr 28 01:31:17 ceew-vm bash[11665]:         from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
Apr 28 01:31:17 ceew-vm bash[11665]:       File "/opt/tljh/user/lib/python3.7/site-packages/jupyter_server/__init__.py", line 15, in <module>
Apr 28 01:31:17 ceew-vm bash[11665]:         from ._version import version_info, __version__
Apr 28 01:31:17 ceew-vm bash[11665]:       File "/opt/tljh/user/lib/python3.7/site-packages/jupyter_server/_version.py", line 5, in <module>
Apr 28 01:31:17 ceew-vm bash[11665]:         from jupyter_packaging import get_version_info
Apr 28 01:31:17 ceew-vm bash[11665]:       File "/opt/tljh/user/lib/python3.7/site-packages/jupyter_packaging/__init__.py", line 7, in <module>
Apr 28 01:31:17 ceew-vm bash[11665]:         from .setupbase import *
Apr 28 01:31:17 ceew-vm bash[11665]:       File "/opt/tljh/user/lib/python3.7/site-packages/jupyter_packaging/setupbase.py", line 38, in <module>
Apr 28 01:31:17 ceew-vm bash[11665]:         from setuptools.config import StaticModule
Apr 28 01:31:17 ceew-vm bash[11665]:     ImportError: cannot import name 'StaticModule' from 'setuptools.config' (/opt/tljh/user/lib/python3.7/site-packages/setuptools/config.py)
Apr 28 01:31:17 ceew-vm bash[11665]: [I 2021-04-28 01:31:17.721 SingleUserNotebookApp extension:22] nteract extension loaded from /opt/tljh/user/lib/python3.7/site-packages/nteract_on_jupyter
```

**Comment by vivekpradhan** [comment]
I tried to install setuptool using pip but it says requirement already satisfied. Any help figuring this out is appreciated. Thanks.

**Comment by vivekpradhan** [comment]
I could not figure this out. I ended up deploying just using `jupyter lab` and warning users not to use concurrently. Closing the issue.
