### ISSUE TITLE
Restart TLJH Docker Container - no Web-Interface

### ISSUE THREAD

**Issue by cablesky** [jupyterhub/the-littlest-jupyterhub#702]
If i restart the TLJH-Docker-Container, i have no Access to the Web Interface.
If i try the command 
`python3 /srv/src/bootstrap/bootstrap.py --admin admin`

i get the following error message.
`Setting up JupyterHub...
Failed to connect to bus: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 442, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 431, in main
    ensure_jupyterhub_service(HUB_ENV_PREFIX)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 73, in ensure_jupyterhub_service
    systemd.reload_daemon()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/systemd.py", line 19, in reload_daemon
    ], check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['systemctl', 'daemon-reload']' returned non-zero exit status 1.`

How can i restart TLJH?

**Comment by jonasjancarik** [comment]
Same issue here. Also there are no journal logs - maybe because the startup fails too early for any logs to be produced.
