### ISSUE TITLE
Install error Ubuntu 20.04 header pyconfig.h not found

### ISSUE THREAD

**Issue by alxsimon** [jupyterhub/the-littlest-jupyterhub#708]
Hi,

### Bug description
I have a compilation error when trying to install the-littlest-jupyterhub, at the point of installing ruamel.yaml.
python3-dev is installed as required.
The header /usr/include/x86_64-linux-gnu/python3.8/pyconfig.h is present on the machine but it does not seem to be picked up.

Maybe an issue with the miniconda compiler being used, I don't know?

```
    building '_ruamel_yaml' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/ext
    /opt/miniconda3/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /opt/miniconda3/include -fPIC -I/opt/tljh/hub/include -I/usr/include/python3.8 -c ext/_ruamel_yaml.c -o build/temp.linux-x86_64-3.8/ext/_ruamel_yaml.o
    In file included from /usr/include/python3.8/Python.h:8,
                     from ext/_ruamel_yaml.c:4:
    /usr/include/python3.8/pyconfig.h:3:12: fatal error: x86_64-linux-gnu/python3.8/pyconfig.h: No such file or directory
        3 | #  include <x86_64-linux-gnu/python3.8/pyconfig.h>
          |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/opt/miniconda3/bin/x86_64-conda-linux-gnu-cc' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of ruamel.yaml
  Moving to /opt/tljh/hub/lib/python3.8/site-packages/ruamel.yaml-0.17.16-py3.9-nspkg.pth
   from /tmp/pip-uninstall-n6hloltu/ruamel.yaml-0.17.16-py3.9-nspkg.pth
  Moving to /opt/tljh/hub/lib/python3.8/site-packages/ruamel.yaml-0.17.16.dist-info/
   from /opt/tljh/hub/lib/python3.8/site-packages/~uamel.yaml-0.17.16.dist-info
  Moving to /opt/tljh/hub/lib/python3.8/site-packages/ruamel/yaml/
   from /opt/tljh/hub/lib/python3.8/site-packages/ruamel/~aml
ERROR: Command errored out with exit status 1: /opt/tljh/hub/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4sinyc1k/ruamel.yaml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4sinyc1k/ruamel.yaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yitwxptb/install-record.txt --single-version-externally-managed --compile --install-headers /opt/tljh/hub/include/site/python3.8/ruamel.yaml Check the logs for full command output.

/home/alexis/.local/lib/python3.8/site-packages/requests/__init__.py:78: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({0}) or chardet ({1}) doesn't match a supported "
Traceback (most recent call last):
  File "<stdin>", line 324, in <module>
  File "<stdin>", line 307, in main
  File "<stdin>", line 140, in run_subprocess
subprocess.CalledProcessError: Command '['/opt/tljh/hub/bin/pip', 'install', '--upgrade', 'git+https://github.com/jupyterhub/the-littlest-jupyterhub.git']' returned non-zero exit status 1.
```

**Comment by consideRatio** [comment]
I'm not sure what this specific error is about, but I think we will need a release of jupyterhub/traefik-proxy have support for this no matter if this specific error is worked around.

**Comment by alxsimon** [comment]
Ooops sorry it's on Ubuntu server 20.04 (scrambled the versions of my different computers when posting this issue). This is Ubuntu server 20.04 on a Dell workstation.
