### ISSUE TITLE
simple plugin fails

### ISSUE THREAD

**Issue by raybellwaves** [jupyterhub/the-littlest-jupyterhub#783]
### Bug description
Copying the example here https://tljh.jupyter.org/en/latest/contributing/plugins.html in https://github.com/raybellwaves/tljh-plugin. I'm not releasing on pypi or using branches for development purpose. I have a build script of

```
#!/bin/bash
curl -L https://tljh.jupyter.org/bootstrap.py \
  | sudo python3 - \
    --admin user --show-progress-page \
    --plugin git+https://github.com/raybellwaves/tljh-plugin@v0.1
```

The gives a Version issue (first Traceback below).

If I take the version out of the setup.py and run `--plugin git+https://github.com/raybellwaves/tljh-plugin` I get `ModuleNotFoundError: No module named 'tljh_plugin'` (second Traceback below). I also tried `--plugin git+https://github.com/raybellwaves/tljh-plugin@main` but got the same error.

first Traceback:
```
[   95.435383] cloud-init[1126]: Ran /opt/tljh/hub/bin/python -m pip install --upgrade git+https://github.com/raybellwaves/tljh-plugin@v0.1 with exit code 1
[   95.452347] cloud-init[1126]: Collecting git+https://github.com/raybellwaves/tljh-plugin@v0.1
[   95.463260] cloud-init[1126]:   Cloning https://github.com/raybellwaves/tljh-plugin (to revision v0.1) to /tmp/pip-req-build-s4coengg
[   95.471262] cloud-init[1126]:   Running command git clone --filter=blob:none -q https://github.com/raybellwaves/tljh-plugin /tmp/pip-req-build-s4coengg
[   95.487565] cloud-init[1126]:   WARNING: Did not find branch or tag 'v0.1', assuming revision or ref.
[   95.495539] cloud-init[1126]:   Running command git checkout -q v0.1
[   95.499023] cloud-init[1126]:   error: pathspec 'v0.1' did not match any file(s) known to git
[   95.503713] cloud-init[1126]: WARNING: Discarding git+https://github.com/raybellwaves/tljh-plugin@v0.1. Command errored out with exit status 1: git checkout -q v0.1 Check the logs for full command output.
[   95.514738] cloud-init[1126]: ERROR: Command errored out with exit status 1: git checkout -q v0.1 Check the logs for full command output.
[   95.524242] cloud-init[1126]: Traceback (most recent call last):
[   95.529036] cloud-init[1126]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[   95.537264] cloud-init[1126]:     return _run_code(code, main_globals, None,
[   95.541153] cloud-init[1126]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[   95.545125] cloud-init[1126]:     exec(code, run_globals)
[   95.551664] cloud-init[1126]:   File "/opt/tljh/hub/lib/python3.8/site-packages/tljh/installer.py", line 475, in <module>
[   95.559235] cloud-init[1126]:     main()
[   95.562154] cloud-init[1126]:   File "/opt/tljh/hub/lib/python3.8/site-packages/tljh/installer.py", line 444, in main
[   95.570245] cloud-init[1126]:     pm = setup_plugins(args.plugin)
[   95.574885] cloud-init[1126]:   File "/opt/tljh/hub/lib/python3.8/site-packages/tljh/installer.py", line 332, in setup_plugins
[   95.583086] cloud-init[1126]:     conda.ensure_pip_packages(HUB_ENV_PREFIX, plugins, upgrade=True)
[   95.590273] cloud-init[1126]:   File "/opt/tljh/hub/lib/python3.8/site-packages/tljh/conda.py", line 145, in ensure_pip_packages
[   95.599876] cloud-init[1126]:     utils.run_subprocess(pip_cmd + packages)
[   95.604717] cloud-init[1126]:   File "/opt/tljh/hub/lib/python3.8/site-packages/tljh/utils.py", line 39, in run_subprocess
[   95.611623] cloud-init[1126]:     raise subprocess.CalledProcessError(cmd=cmd, returncode=proc.returncode)
[   95.617757] cloud-init[1126]: subprocess.CalledProcessError: Command '['/opt/tljh/hub/bin/python', '-m', 'pip', 'install', '--upgrade', 'git+https://github.com/raybellwaves/tljh-plugin@v0.1']' returned non-zero exit status 1.
[   95.629929] cloud-init[1126]: Cloud-init v. 21.4-0ubuntu1~20.04.1 running 'modules:final' at Sun, 19 Dec 2021 04:11:31 +0000. Up 21.79 seconds.
[   95.642629] cloud-init[1126]: 2021-12-19 04:12:45,457 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
[   95.649653] cloud-init[1126]: 2021-12-19 04:12:45,458 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
```

Second trackback
```
[   68.220483] cloud-init[1129]: Setting up virtual environment at /opt/tljh/hub
[   70.250326] cloud-init[1129]: Upgrading pip...
[   72.926410] cloud-init[1129]: Installing TLJH installer...
[   86.748631] cloud-init[1129]: Running TLJH installer...
[   88.627776] cloud-init[1129]: Traceback (most recent call last):
[   88.634820] cloud-init[1129]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[   88.640461] cloud-init[1129]:     return _run_code(code, main_globals, None,
[   88.646979] cloud-init[1129]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[   88.659033] cloud-init[1129]:     exec(code, run_globals)
[   88.666943] cloud-init[1129]:   File "/opt/tljh/hub/lib/python3.8/site-packages/tljh/installer.py", line 475, in <module>
[   88.679037] cloud-init[1129]:     main()
[   88.681311] cloud-init[1129]:   File "/opt/tljh/hub/lib/python3.8/site-packages/tljh/installer.py", line 444, in main
[   88.691252] cloud-init[1129]:     pm = setup_plugins(args.plugin)
[   88.696404] cloud-init[1129]:   File "/opt/tljh/hub/lib/python3.8/site-packages/tljh/installer.py", line 337, in setup_plugins
[   88.702631] cloud-init[1129]:     pm.load_setuptools_entrypoints("tljh")
[   88.707668] cloud-init[1129]:   File "/opt/tljh/hub/lib/python3.8/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
[   88.714814] cloud-init[1129]:     plugin = ep.load()
[   88.718280] cloud-init[1129]:   File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
[   88.723336] cloud-init[1129]:     module = import_module(match.group('module'))
[   88.727640] cloud-init[1129]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
[   88.733095] cloud-init[1129]:     return _bootstrap._gcd_import(name[level:], package, level)
[   88.739060] cloud-init[1129]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[   88.745920] cloud-init[1129]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[   88.750969] cloud-init[1129]:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
[   88.756930] cloud-init[1129]: ModuleNotFoundError: No module named 'tljh_plugin'
```

**Comment by raybellwaves** [comment]
nvm file named `plugin.py` instead of `tljh_plugin.py`
