### ISSUE TITLE
suddenly all kernels crashed

### ISSUE THREAD

**Issue by LukaPitamic** [jupyterhub/the-littlest-jupyterhub#790]
### Bug description
All kernels suddenly got killed in non-admin _tljh_ account. 
This all happened when we added the code-line to notebook:
```python
# if some condition:
    rase Exception('some message')
```
which was run concurrently (using _acynco_ package) 
...this might or might have not contributed to kernels crash

### _tljh_ set up
1. setup versions:  
   - ubuntu: 20.04
   - JupyterLab: 3.1.18
   - JupyterHub: 1.4.0 20211203040509
   - python: 3.73
2. <details><summary>Full environment</summary>
```
aiohttp==3.7.4.post0
alembic==1.7.3
ansi2html @ file:///home/conda/feedstock_root/build_artifacts/ansi2html_1610127419299/work
ansiwrap==0.8.4
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1632754239140/work/dist
argcomplete==1.12.3
argon2-cffi==21.1.0
asn1crypto==0.24.0
astropy==4.3.1
async-generator==1.10
async-timeout==3.0.1
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1620387926260/work
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1619719576210/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
beautifulsoup4==4.10.0
black==21.9b0
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1629908509068/work
Bottleneck==1.3.2
Brotli @ file:///home/conda/feedstock_root/build_artifacts/brotli-split_1603546189128/work
bs4==0.0.1
cached-property==1.5.2
cachetools==4.2.4
ccxt==1.56.63
certifi==2021.10.8
certipy==0.1.3
cffi==1.12.3
chardet==3.0.4
click @ file:///home/conda/feedstock_root/build_artifacts/click_1621503711357/work
colorama==0.4.4
colorlover==0.3.0
commonmark==0.9.1
conda==4.10.3
conda-package-handling==1.3.11
cryptography==2.7
cssselect==1.1.0
cssutils==2.3.0
cycler==0.10.0
dash @ file:///home/conda/feedstock_root/build_artifacts/dash_1632235402030/work
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
dataclasses @ file:///home/conda/feedstock_root/build_artifacts/dataclasses_1628958434797/work
debugpy==1.4.3
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1631346842025/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
deprecation==2.1.0
dill==0.3.4
echo==0.5
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1605121927639/work/dist/entrypoints-0.3-py2.py3-none-any.whl
et-xmlfile==1.1.0
fast-histogram==0.10
Flask==2.0.1
Flask-Compress==1.10.1
floatview==0.3.1
freetype-py==2.2.0
gitdb==4.0.7
GitPython==3.1.24
glue-core==1.2.2
glue-vispy-viewers==1.0.3
glueviz==1.2.0
greenlet==1.1.2
h5py==3.4.0
hsluv==5.0.2
idna==2.8
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1630267469306/work
importlib-resources==5.2.2
ipykernel==6.4.1
ipynbname==2021.3.2
ipyparams==0.2.1
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1632763775723/work
ipython-genutils==0.2.0
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1631590360471/work
itsdangerous @ file:///home/conda/feedstock_root/build_artifacts/itsdangerous_1621360792037/work
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1610146791823/work
Jinja2==3.0.1
joblib==1.0.1
json5==0.9.6
jsonschema==4.0.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1630690655192/work
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1631852710654/work
jupyter-dash @ file:///home/conda/feedstock_root/build_artifacts/jupyter-dash_1611351072022/work
jupyter-packaging==0.10.6
jupyter-resource-usage==0.5.1
jupyter-server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1631218027728/work
jupyter-server-mathjax==0.2.3
jupyter-spaces==0.2.1
jupyter-telemetry==0.1.0
jupyterhub==1.4.0
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1633634490182/work
jupyterlab-drawio==0.9.0
jupyterlab-git==0.33.0
jupyterlab-gt-coar-theme==0.3.0
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1632590716858/work
jupyterlab-simpledark==1.0.0
jupyterlab-spellchecker @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab-spellchecker_1630525443156/work
jupyterlab-sublime @ file:///opt/tljh/ET-key_bindings/dist/jupyterlab_sublime-0.4.1-py3-none-any.whl
jupyterlab-templates==0.3.1
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1631590465624/work
kaleido @ file:///home/jmmease/anaconda3/conda-bld/python-kaleido_1596620303641/work/kaleido-0.0.3-py2.py3-none-manylinux2014_x86_64.whl
kiwisolver==1.3.2
libarchive-c==2.8
lxml==4.6.3
Mako==1.1.5
MarkupSafe==2.0.1
matplotlib==3.4.3
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1631080358261/work
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1605115652256/work
mkl-fft==1.3.0
mkl-random @ file:///tmp/build/80754af9/mkl_random_1626179032232/work
mkl-service==2.4.0
mpl-scatter-density==0.7
multidict==5.1.0
mypy-extensions==0.4.3
nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1631880505492/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1629120697898/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert_1632535944093/work
nbdime==3.1.0
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1617383142101/work
nbgitpuller==0.9.0
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1617163391303/work
networkx==2.6.3
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1631733685426/work
nteract-on-jupyter==2.1.3
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1626264701743/work
oauthlib==3.1.1
openpyxl==3.0.9
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1625323647219/work
pamela==1.0.0
pandas==1.3.3
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
papermill==2.3.3
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1617148930513/work
pathspec==0.9.0
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1602535608087/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==8.3.2
pip-search==0.0.7
platformdirs==2.4.0
plotly @ file:///Users/nicolas/opt/miniconda3/envs/env/conda-bld/plotly_1630459557113/work/packages/python/plotly/dist/plotly-5.3.1.tar.gz
premailer==3.10.0
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1622586138406/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1629903925368/work
psutil==5.8.0
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pycares==4.0.0
pycoingecko==2.0.0
pycosat==0.6.3
pycparser==2.19
pyerfa==2.0.0
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1629119114968/work
PyOpenGL==3.1.5
pyOpenSSL==19.0.0
pyparsing==2.4.7
pyrsistent==0.18.0
PySocks==1.7.0
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-json-logger==2.0.2
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1612179539967/work
PyYAML==5.4.1
pyzmq==22.3.0
qgrid==1.3.1
qtconsole==5.1.1
QtPy==1.11.2
regex==2021.9.24
requests==2.22.0
requests-unixsocket==0.2.0
retrying==1.3.3
rich==10.12.0
ruamel-yaml==0.15.46
ruamel.yaml.clib==0.2.6
schedule==1.1.0
scikit-learn==1.0
scipy @ file:///tmp/build/80754af9/scipy_1630606797510/work
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1628511208346/work
sidecar @ file:///home/conda/feedstock_root/build_artifacts/sidecar_1616054965882/work
six==1.12.0
smmap==4.0.0
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1610318316464/work
soupsieve==2.2.1
SQLAlchemy==1.4.25
TA-Lib==0.4.21
tenacity @ file:///tmp/build/80754af9/tenacity_1632746495287/work
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1631128156863/work
testpath @ file:///home/conda/feedstock_root/build_artifacts/testpath_1621261527237/work
textwrap3==0.9.2
threadpoolctl==2.2.0
tomli==1.2.1
tomlkit==0.7.2
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1604105014127/work
tqdm @ file:///tmp/build/80754af9/tqdm_1635330843403/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1630423529112/work
typed-ast==1.4.3
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1632313171031/work
urllib3==1.24.2
vispy==0.9.0
voila==0.2.15
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
webencodings==0.5.1
websocket-client==1.2.1
Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1621518206714/work
widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1605475530234/work
xlrd==2.0.1
yagmail==0.14.260
yarl==1.6.3
zipp==3.6.0
```
</details>

3. <details><summary>Configuration</summary>

```python
"""
JupyterHub config for the littlest jupyterhub.
"""
from glob import glob
import os
from systemdspawner import SystemdSpawner
from tljh import configurer
from tljh.config import INSTALL_PREFIX, USER_ENV_PREFIX, CONFIG_DIR
from tljh.utils import get_plugin_manager
from tljh.user_creating_spawner import UserCreatingSpawner
from jupyterhub_traefik_proxy import TraefikTomlProxy
c.JupyterHub.spawner_class = UserCreatingSpawner
c.JupyterHub.cleanup_servers = False
c.JupyterHub.hub_port = 15001
c.TraefikTomlProxy.should_start = False
dynamic_conf_file_path = os.path.join(INSTALL_PREFIX, 'state', 'rules', 'rules.toml')
c.TraefikTomlProxy.toml_dynamic_config_file = dynamic_conf_file_path
c.JupyterHub.proxy_class = TraefikTomlProxy
c.SystemdSpawner.extra_paths = [os.path.join(USER_ENV_PREFIX, 'bin')]
c.SystemdSpawner.default_shell = '/bin/bash'
c.SystemdSpawner.unit_name_template = 'jupyter-{USERNAME}'
tljh_config = configurer.load_config()
configurer.apply_config(tljh_config, c)
pm = get_plugin_manager()
pm.hook.tljh_custom_jupyterhub_config(c=c)
extra_configs = sorted(glob(os.path.join(CONFIG_DIR, 'jupyterhub_config.d', '*.py')))
for ec in extra_configs:
    load_subconfig(ec)
```
</details>

- <details><summary>Logs - relevant section of _User Server Log_</summary>

```
Jan 05 05:36:36 jupyterhub bash[2034226]: [IPKernelApp] ERROR | Error in message handler
Jan 05 05:36:36 jupyterhub bash[2034226]: Traceback (most recent call last):
Jan 05 05:36:36 jupyterhub bash[2034226]:   File "/opt/tljh/user/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 374, in >
Jan 05 05:36:36 jupyterhub bash[2034226]:     yield self.process_one()
Jan 05 05:36:36 jupyterhub bash[2034226]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
Jan 05 05:36:36 jupyterhub bash[2531819]: [I 2022-01-05 05:36:36.292 SingleUserNotebookApp kernelmanager:287] Discarding 11045 buffe>
Jan 05 05:36:36 jupyterhub bash[2531819]: [I 2022-01-05 05:36:36.309 SingleUserNotebookApp multikernelmanager:212] Kernel shutdown: >
Jan 05 05:36:36 jupyterhub bash[2531819]: [I 2022-01-05 05:36:36.311 SingleUserNotebookApp multikernelmanager:212] Kernel shutdown: >
Jan 05 05:36:36 jupyterhub bash[2034226]: [IPKernelApp] ERROR | Error in message handler
Jan 05 05:36:36 jupyterhub bash[2034226]: Traceback (most recent call last):
Jan 05 05:36:36 jupyterhub bash[2034226]:   File "/opt/tljh/user/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 374, in >
Jan 05 05:36:36 jupyterhub bash[2034226]:     yield self.process_one()
Jan 05 05:36:36 jupyterhub bash[2034226]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
Jan 05 05:36:36 jupyterhub bash[2034226]:     value = future.result()
Jan 05 05:36:36 jupyterhub bash[2034226]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
Jan 05 05:36:36 jupyterhub bash[2034226]:     yielded = self.gen.throw(*exc_info)  # type: ignore
Jan 05 05:36:36 jupyterhub bash[2034226]:   File "/opt/tljh/user/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 358, in >
Jan 05 05:36:36 jupyterhub bash[2034226]:     yield gen.maybe_future(dispatch(*args))
Jan 05 05:36:36 jupyterhub bash[2034226]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
Jan 05 05:36:36 jupyterhub bash[2034226]:     value = future.result()
Jan 05 05:36:36 jupyterhub bash[2034226]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
Jan 05 05:36:36 jupyterhub bash[2034226]:     yielded = ctx_run(next, result)
Jan 05 05:36:36 jupyterhub bash[2034226]:   File "/opt/tljh/user/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 182, in >
Jan 05 05:36:36 jupyterhub bash[2034226]:     self.set_parent(idents, msg)
Jan 05 05:36:36 jupyterhub bash[2034226]:   File "/opt/tljh/user/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 153, in se>
Jan 05 05:36:36 jupyterhub bash[2034226]:     self.shell.set_parent(parent)
Jan 05 05:36:36 jupyterhub bash[2034226]:   File "/opt/tljh/user/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 580, in se>
Jan 05 05:36:36 jupyterhub bash[2034226]:     self.display_pub.set_parent(parent)
Jan 05 05:36:36 jupyterhub bash[2034226]: AttributeError: 'CapturingDisplayPublisher' object has no attribute 'set_parent'
Jan 05 05:36:36 jupyterhub bash[2531819]: [I 2022-01-05 05:36:36.609 SingleUserNotebookApp multikernelmanager:212] Kernel shutdown: >
Jan 05 05:36:36 jupyterhub bash[2034091]: [IPKernelApp] ERROR | Error in message handler
Jan 05 05:36:36 jupyterhub bash[2034091]: Traceback (most recent call last):
Jan 05 05:36:36 jupyterhub bash[2034091]:   File "/opt/tljh/user/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 374, in >
Jan 05 05:36:36 jupyterhub bash[2034091]:     yield self.process_one()
Jan 05 05:36:36 jupyterhub bash[2034091]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
Jan 05 05:36:36 jupyterhub bash[2034091]:     value = future.result()
Jan 05 05:36:36 jupyterhub bash[2034091]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
Jan 05 05:36:36 jupyterhub bash[2034091]:     yielded = self.gen.throw(*exc_info)  # type: ignore
Jan 05 05:36:36 jupyterhub bash[2034091]:   File "/opt/tljh/user/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 358, in >
Jan 05 05:36:36 jupyterhub bash[2034091]:     yield gen.maybe_future(dispatch(*args))
Jan 05 05:36:36 jupyterhub bash[2034091]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
Jan 05 05:36:36 jupyterhub bash[2034091]:     value = future.result()
Jan 05 05:36:36 jupyterhub bash[2034091]:   File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
Jan 05 05:36:36 jupyterhub bash[2034091]:     yielded = ctx_run(next, result)
Jan 05 05:36:36 jupyterhub bash[2034091]:   File "/opt/tljh/user/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 182, in >
Jan 05 05:36:36 jupyterhub bash[2034091]:     self.set_parent(idents, msg)
Jan 05 05:36:36 jupyterhub bash[2034091]:   File "/opt/tljh/user/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 153, in se>
Jan 05 05:36:36 jupyterhub bash[2034091]:     self.shell.set_parent(parent)
Jan 05 05:36:36 jupyterhub bash[2034091]:   File "/opt/tljh/user/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 580, in se>
Jan 05 05:36:36 jupyterhub bash[2034091]:     self.display_pub.set_parent(parent)
Jan 05 05:36:36 jupyterhub bash[2034091]: AttributeError: 'CapturingDisplayPublisher' object has no attribute 'set_parent'
Jan 05 05:36:36 jupyterhub bash[2531819]: [I 2022-01-05 05:36:36.621 SingleUserNotebookApp multikernelmanager:212] Kernel shutdown: >


```
</details>

**Comment by manics** [comment]
This sounds like a problem with the JupyterLab/notebook environment rather than TLJH.

In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions.
