### ISSUE TITLE
Virtual environment "user" not loaded when spawning

### ISSUE THREAD

**Issue by MattMuffin** [jupyterhub/the-littlest-jupyterhub#940]
### Bug description

The following message is displayed when trying to launch the server (found using sudo journalctl -xeu jupyter-[USER].service -f )

Traceback (most recent call last):
File "/opt/tljh/user/bin/jupyterhub-singleuser", line 5, in <module>
 from jupyterhub.singleuser import main
File "/opt/tljh/user/lib/python3.10/site-packages/jupyterhub/singleuser/__init__.py", line 17, in <module>
 from .mixins import HubAuthenticatedHandler, make_singleuser_app
File "/opt/tljh/user/lib/python3.10/site-packages/jupyterhub/singleuser/mixins.py", line 26, in <module>
from tornado import ioloop
**ModuleNotFoundError: No module named 'tornado'**

### How to reproduce

Follow the install instructions here:

https://tljh.jupyter.org/en/latest/install/custom-server.html

`sudo apt install python3 python3-dev git curl
curl -L https://tljh.jupyter.org/bootstrap.py | sudo -E python3 - --admin <admin-user-name>
`

#### Expected behaviour

Server successfully  launch

#### Actual behaviour

Error message regarding a module not being found

### Your personal set up

 - OS:
 ubuntu 22.04
python 3.10.10

 
 - Version(s):
 

<details><summary>Full environment</summary>

call the virtualenv: source /opt/jupyterhub/user/bin/activate
then check pip list

Package                   Version
------------------------- ---------
alembic                   1.12.0
anyio                     4.0.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.2.3
asttokens                 2.4.0
async-generator           1.10
async-lru                 2.0.4
attrs                     23.1.0
Babel                     2.12.1
backcall                  0.2.0
beautifulsoup4            4.12.2
bleach                    6.0.0
brotlipy                  0.7.0
certifi                   2022.12.7
certipy                   0.1.3
cffi                      1.15.1
charset-normalizer        3.2.0
colorama                  0.4.6
comm                      0.1.4
conda                     23.1.0
conda-package-handling    2.0.2
conda_package_streaming   0.7.0
cryptography              40.0.1
debugpy                   1.8.0
decorator                 5.1.1
defusedxml                0.7.1
exceptiongroup            1.1.3
executing                 1.2.0
fastjsonschema            2.18.0
fqdn                      1.5.1
greenlet                  2.0.2
idna                      3.4
ipykernel                 6.25.2
ipython                   8.15.0
ipywidgets                8.1.1
isoduration               20.11.0
jedi                      0.19.0
Jinja2                    3.1.2
json5                     0.9.14
jsonpointer               2.4
jsonschema                4.19.0
jsonschema-specifications 2023.7.1
jupyter_client            8.3.1
jupyter_core              5.3.1
jupyter-events            0.7.0
jupyter-lsp               2.2.0
jupyter-resource-usage    1.0.1
jupyter_server            2.7.3
jupyter_server_terminals  0.4.4
jupyter-telemetry         0.1.0
jupyterhub                4.0.2
jupyterlab                4.0.6
jupyterlab-pygments       0.2.2
jupyterlab_server         2.25.0
jupyterlab-widgets        3.0.9
libmambapy                1.4.1
Mako                      1.2.4
mamba                     1.4.1
MarkupSafe                2.1.3
matplotlib-inline         0.1.6
mistune                   3.0.1
nbclient                  0.8.0
nbconvert                 7.8.0
nbformat                  5.9.2
nbgitpuller               1.2.0
nest-asyncio              1.5.8
notebook                  7.0.3
notebook_shim             0.2.3
oauthlib                  3.2.2
overrides                 7.4.0
packaging                 23.1
pamela                    1.1.0
pandocfilters             1.5.0
parso                     0.8.3
pexpect                   4.8.0
pickleshare               0.7.5
pip                       23.2.1
platformdirs              3.10.0
pluggy                    1.0.0
prometheus-client         0.17.1
prompt-toolkit            3.0.39
psutil                    5.9.5
ptyprocess                0.7.0
pure-eval                 0.2.2
pycosat                   0.6.4
pycparser                 2.21
Pygments                  2.16.1
pyOpenSSL                 23.1.1
PySocks                   1.7.1
python-dateutil           2.8.2
python-json-logger        2.0.7
PyYAML                    6.0.1
pyzmq                     25.1.1
referencing               0.30.2
requests                  2.31.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.10.3
ruamel.yaml               0.17.32
ruamel.yaml.clib          0.2.7
Send2Trash                1.8.2
setuptools                65.6.3
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.5
SQLAlchemy                2.0.20
stack-data                0.6.2
terminado                 0.17.1
tinycss2                  1.2.1
tomli                     2.0.1
toolz                     0.12.0
**tornado                   6.3.3**
tqdm                      4.65.0
traitlets                 5.10.0
typing_extensions         4.8.0
uri-template              1.3.0
urllib3                   1.26.15
wcwidth                   0.2.6
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.6.3
wheel                     0.40.0
widgetsnbextension        4.0.9
zstandard                 0.19.0
```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by ibeatty** [comment]
I just got bit by this one. It seems to have been reported well over a year ago, and is still listed as "open". Does anyone at least have a workaround?
